
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Activity
 * *
 *  * Activity Logs - User actions and events
 */
export type Activity = Prisma.ActivityModel
/**
 * Model EmailLog
 * *
 *  * Email Logs - Sent email tracking
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model Achievement
 * *
 *  * Achievement System
 */
export type Achievement = Prisma.AchievementModel
/**
 * Model UserAchievement
 * 
 */
export type UserAchievement = Prisma.UserAchievementModel
/**
 * Model EloHistory
 * *
 *  * ELO History - Track rating changes over time (future)
 */
export type EloHistory = Prisma.EloHistoryModel
