
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SessionPairHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SessionPairHistory
 * *
 *  * ============================================================
 *  * TOURNAMENTS
 *  * ============================================================
 */
export type SessionPairHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionPairHistoryPayload>

export type AggregateSessionPairHistory = {
  _count: SessionPairHistoryCountAggregateOutputType | null
  _min: SessionPairHistoryMinAggregateOutputType | null
  _max: SessionPairHistoryMaxAggregateOutputType | null
}

export type SessionPairHistoryMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  playerA: string | null
  playerB: string | null
  createdAt: Date | null
}

export type SessionPairHistoryMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  playerA: string | null
  playerB: string | null
  createdAt: Date | null
}

export type SessionPairHistoryCountAggregateOutputType = {
  id: number
  sessionId: number
  playerA: number
  playerB: number
  createdAt: number
  _all: number
}


export type SessionPairHistoryMinAggregateInputType = {
  id?: true
  sessionId?: true
  playerA?: true
  playerB?: true
  createdAt?: true
}

export type SessionPairHistoryMaxAggregateInputType = {
  id?: true
  sessionId?: true
  playerA?: true
  playerB?: true
  createdAt?: true
}

export type SessionPairHistoryCountAggregateInputType = {
  id?: true
  sessionId?: true
  playerA?: true
  playerB?: true
  createdAt?: true
  _all?: true
}

export type SessionPairHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPairHistory to aggregate.
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPairHistories to fetch.
   */
  orderBy?: Prisma.SessionPairHistoryOrderByWithRelationInput | Prisma.SessionPairHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionPairHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPairHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPairHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SessionPairHistories
  **/
  _count?: true | SessionPairHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionPairHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionPairHistoryMaxAggregateInputType
}

export type GetSessionPairHistoryAggregateType<T extends SessionPairHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateSessionPairHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSessionPairHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateSessionPairHistory[P]>
}




export type SessionPairHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionPairHistoryWhereInput
  orderBy?: Prisma.SessionPairHistoryOrderByWithAggregationInput | Prisma.SessionPairHistoryOrderByWithAggregationInput[]
  by: Prisma.SessionPairHistoryScalarFieldEnum[] | Prisma.SessionPairHistoryScalarFieldEnum
  having?: Prisma.SessionPairHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionPairHistoryCountAggregateInputType | true
  _min?: SessionPairHistoryMinAggregateInputType
  _max?: SessionPairHistoryMaxAggregateInputType
}

export type SessionPairHistoryGroupByOutputType = {
  id: string
  sessionId: string
  playerA: string
  playerB: string
  createdAt: Date
  _count: SessionPairHistoryCountAggregateOutputType | null
  _min: SessionPairHistoryMinAggregateOutputType | null
  _max: SessionPairHistoryMaxAggregateOutputType | null
}

type GetSessionPairHistoryGroupByPayload<T extends SessionPairHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionPairHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionPairHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionPairHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionPairHistoryGroupByOutputType[P]>
      }
    >
  >



export type SessionPairHistoryWhereInput = {
  AND?: Prisma.SessionPairHistoryWhereInput | Prisma.SessionPairHistoryWhereInput[]
  OR?: Prisma.SessionPairHistoryWhereInput[]
  NOT?: Prisma.SessionPairHistoryWhereInput | Prisma.SessionPairHistoryWhereInput[]
  id?: Prisma.StringFilter<"SessionPairHistory"> | string
  sessionId?: Prisma.StringFilter<"SessionPairHistory"> | string
  playerA?: Prisma.StringFilter<"SessionPairHistory"> | string
  playerB?: Prisma.StringFilter<"SessionPairHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"SessionPairHistory"> | Date | string
}

export type SessionPairHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SessionPairHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  sessionId_playerA_playerB?: Prisma.SessionPairHistorySessionIdPlayerAPlayerBCompoundUniqueInput
  AND?: Prisma.SessionPairHistoryWhereInput | Prisma.SessionPairHistoryWhereInput[]
  OR?: Prisma.SessionPairHistoryWhereInput[]
  NOT?: Prisma.SessionPairHistoryWhereInput | Prisma.SessionPairHistoryWhereInput[]
  sessionId?: Prisma.StringFilter<"SessionPairHistory"> | string
  playerA?: Prisma.StringFilter<"SessionPairHistory"> | string
  playerB?: Prisma.StringFilter<"SessionPairHistory"> | string
  createdAt?: Prisma.DateTimeFilter<"SessionPairHistory"> | Date | string
}, "id" | "sessionId_playerA_playerB">

export type SessionPairHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SessionPairHistoryCountOrderByAggregateInput
  _max?: Prisma.SessionPairHistoryMaxOrderByAggregateInput
  _min?: Prisma.SessionPairHistoryMinOrderByAggregateInput
}

export type SessionPairHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionPairHistoryScalarWhereWithAggregatesInput | Prisma.SessionPairHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionPairHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionPairHistoryScalarWhereWithAggregatesInput | Prisma.SessionPairHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SessionPairHistory"> | string
  sessionId?: Prisma.StringWithAggregatesFilter<"SessionPairHistory"> | string
  playerA?: Prisma.StringWithAggregatesFilter<"SessionPairHistory"> | string
  playerB?: Prisma.StringWithAggregatesFilter<"SessionPairHistory"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SessionPairHistory"> | Date | string
}

export type SessionPairHistoryCreateInput = {
  id?: string
  sessionId: string
  playerA: string
  playerB: string
  createdAt?: Date | string
}

export type SessionPairHistoryUncheckedCreateInput = {
  id?: string
  sessionId: string
  playerA: string
  playerB: string
  createdAt?: Date | string
}

export type SessionPairHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SessionPairHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SessionPairHistoryCreateManyInput = {
  id?: string
  sessionId: string
  playerA: string
  playerB: string
  createdAt?: Date | string
}

export type SessionPairHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SessionPairHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SessionPairHistorySessionIdPlayerAPlayerBCompoundUniqueInput = {
  sessionId: string
  playerA: string
  playerB: string
}

export type SessionPairHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SessionPairHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SessionPairHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type SessionPairHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  playerA?: boolean
  playerB?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sessionPairHistory"]>

export type SessionPairHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  playerA?: boolean
  playerB?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sessionPairHistory"]>

export type SessionPairHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  playerA?: boolean
  playerB?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["sessionPairHistory"]>

export type SessionPairHistorySelectScalar = {
  id?: boolean
  sessionId?: boolean
  playerA?: boolean
  playerB?: boolean
  createdAt?: boolean
}

export type SessionPairHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "playerA" | "playerB" | "createdAt", ExtArgs["result"]["sessionPairHistory"]>

export type $SessionPairHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SessionPairHistory"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string
    playerA: string
    playerB: string
    createdAt: Date
  }, ExtArgs["result"]["sessionPairHistory"]>
  composites: {}
}

export type SessionPairHistoryGetPayload<S extends boolean | null | undefined | SessionPairHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload, S>

export type SessionPairHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionPairHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionPairHistoryCountAggregateInputType | true
  }

export interface SessionPairHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SessionPairHistory'], meta: { name: 'SessionPairHistory' } }
  /**
   * Find zero or one SessionPairHistory that matches the filter.
   * @param {SessionPairHistoryFindUniqueArgs} args - Arguments to find a SessionPairHistory
   * @example
   * // Get one SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionPairHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SessionPairHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionPairHistoryFindUniqueOrThrowArgs} args - Arguments to find a SessionPairHistory
   * @example
   * // Get one SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionPairHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPairHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryFindFirstArgs} args - Arguments to find a SessionPairHistory
   * @example
   * // Get one SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionPairHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SessionPairHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryFindFirstOrThrowArgs} args - Arguments to find a SessionPairHistory
   * @example
   * // Get one SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionPairHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SessionPairHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SessionPairHistories
   * const sessionPairHistories = await prisma.sessionPairHistory.findMany()
   * 
   * // Get first 10 SessionPairHistories
   * const sessionPairHistories = await prisma.sessionPairHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionPairHistoryWithIdOnly = await prisma.sessionPairHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionPairHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SessionPairHistory.
   * @param {SessionPairHistoryCreateArgs} args - Arguments to create a SessionPairHistory.
   * @example
   * // Create one SessionPairHistory
   * const SessionPairHistory = await prisma.sessionPairHistory.create({
   *   data: {
   *     // ... data to create a SessionPairHistory
   *   }
   * })
   * 
   */
  create<T extends SessionPairHistoryCreateArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SessionPairHistories.
   * @param {SessionPairHistoryCreateManyArgs} args - Arguments to create many SessionPairHistories.
   * @example
   * // Create many SessionPairHistories
   * const sessionPairHistory = await prisma.sessionPairHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionPairHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SessionPairHistories and returns the data saved in the database.
   * @param {SessionPairHistoryCreateManyAndReturnArgs} args - Arguments to create many SessionPairHistories.
   * @example
   * // Create many SessionPairHistories
   * const sessionPairHistory = await prisma.sessionPairHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SessionPairHistories and only return the `id`
   * const sessionPairHistoryWithIdOnly = await prisma.sessionPairHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionPairHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SessionPairHistory.
   * @param {SessionPairHistoryDeleteArgs} args - Arguments to delete one SessionPairHistory.
   * @example
   * // Delete one SessionPairHistory
   * const SessionPairHistory = await prisma.sessionPairHistory.delete({
   *   where: {
   *     // ... filter to delete one SessionPairHistory
   *   }
   * })
   * 
   */
  delete<T extends SessionPairHistoryDeleteArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SessionPairHistory.
   * @param {SessionPairHistoryUpdateArgs} args - Arguments to update one SessionPairHistory.
   * @example
   * // Update one SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionPairHistoryUpdateArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SessionPairHistories.
   * @param {SessionPairHistoryDeleteManyArgs} args - Arguments to filter SessionPairHistories to delete.
   * @example
   * // Delete a few SessionPairHistories
   * const { count } = await prisma.sessionPairHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionPairHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionPairHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPairHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SessionPairHistories
   * const sessionPairHistory = await prisma.sessionPairHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionPairHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SessionPairHistories and returns the data updated in the database.
   * @param {SessionPairHistoryUpdateManyAndReturnArgs} args - Arguments to update many SessionPairHistories.
   * @example
   * // Update many SessionPairHistories
   * const sessionPairHistory = await prisma.sessionPairHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SessionPairHistories and only return the `id`
   * const sessionPairHistoryWithIdOnly = await prisma.sessionPairHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionPairHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SessionPairHistory.
   * @param {SessionPairHistoryUpsertArgs} args - Arguments to update or create a SessionPairHistory.
   * @example
   * // Update or create a SessionPairHistory
   * const sessionPairHistory = await prisma.sessionPairHistory.upsert({
   *   create: {
   *     // ... data to create a SessionPairHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SessionPairHistory we want to update
   *   }
   * })
   */
  upsert<T extends SessionPairHistoryUpsertArgs>(args: Prisma.SelectSubset<T, SessionPairHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionPairHistoryClient<runtime.Types.Result.GetResult<Prisma.$SessionPairHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SessionPairHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryCountArgs} args - Arguments to filter SessionPairHistories to count.
   * @example
   * // Count the number of SessionPairHistories
   * const count = await prisma.sessionPairHistory.count({
   *   where: {
   *     // ... the filter for the SessionPairHistories we want to count
   *   }
   * })
  **/
  count<T extends SessionPairHistoryCountArgs>(
    args?: Prisma.Subset<T, SessionPairHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionPairHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SessionPairHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionPairHistoryAggregateArgs>(args: Prisma.Subset<T, SessionPairHistoryAggregateArgs>): Prisma.PrismaPromise<GetSessionPairHistoryAggregateType<T>>

  /**
   * Group by SessionPairHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionPairHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionPairHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionPairHistoryGroupByArgs['orderBy'] }
      : { orderBy?: SessionPairHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionPairHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionPairHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SessionPairHistory model
 */
readonly fields: SessionPairHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SessionPairHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionPairHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SessionPairHistory model
 */
export interface SessionPairHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"SessionPairHistory", 'String'>
  readonly sessionId: Prisma.FieldRef<"SessionPairHistory", 'String'>
  readonly playerA: Prisma.FieldRef<"SessionPairHistory", 'String'>
  readonly playerB: Prisma.FieldRef<"SessionPairHistory", 'String'>
  readonly createdAt: Prisma.FieldRef<"SessionPairHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SessionPairHistory findUnique
 */
export type SessionPairHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter, which SessionPairHistory to fetch.
   */
  where: Prisma.SessionPairHistoryWhereUniqueInput
}

/**
 * SessionPairHistory findUniqueOrThrow
 */
export type SessionPairHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter, which SessionPairHistory to fetch.
   */
  where: Prisma.SessionPairHistoryWhereUniqueInput
}

/**
 * SessionPairHistory findFirst
 */
export type SessionPairHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter, which SessionPairHistory to fetch.
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPairHistories to fetch.
   */
  orderBy?: Prisma.SessionPairHistoryOrderByWithRelationInput | Prisma.SessionPairHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPairHistories.
   */
  cursor?: Prisma.SessionPairHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPairHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPairHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPairHistories.
   */
  distinct?: Prisma.SessionPairHistoryScalarFieldEnum | Prisma.SessionPairHistoryScalarFieldEnum[]
}

/**
 * SessionPairHistory findFirstOrThrow
 */
export type SessionPairHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter, which SessionPairHistory to fetch.
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPairHistories to fetch.
   */
  orderBy?: Prisma.SessionPairHistoryOrderByWithRelationInput | Prisma.SessionPairHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SessionPairHistories.
   */
  cursor?: Prisma.SessionPairHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPairHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPairHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SessionPairHistories.
   */
  distinct?: Prisma.SessionPairHistoryScalarFieldEnum | Prisma.SessionPairHistoryScalarFieldEnum[]
}

/**
 * SessionPairHistory findMany
 */
export type SessionPairHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter, which SessionPairHistories to fetch.
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SessionPairHistories to fetch.
   */
  orderBy?: Prisma.SessionPairHistoryOrderByWithRelationInput | Prisma.SessionPairHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SessionPairHistories.
   */
  cursor?: Prisma.SessionPairHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SessionPairHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SessionPairHistories.
   */
  skip?: number
  distinct?: Prisma.SessionPairHistoryScalarFieldEnum | Prisma.SessionPairHistoryScalarFieldEnum[]
}

/**
 * SessionPairHistory create
 */
export type SessionPairHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * The data needed to create a SessionPairHistory.
   */
  data: Prisma.XOR<Prisma.SessionPairHistoryCreateInput, Prisma.SessionPairHistoryUncheckedCreateInput>
}

/**
 * SessionPairHistory createMany
 */
export type SessionPairHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SessionPairHistories.
   */
  data: Prisma.SessionPairHistoryCreateManyInput | Prisma.SessionPairHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SessionPairHistory createManyAndReturn
 */
export type SessionPairHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many SessionPairHistories.
   */
  data: Prisma.SessionPairHistoryCreateManyInput | Prisma.SessionPairHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SessionPairHistory update
 */
export type SessionPairHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * The data needed to update a SessionPairHistory.
   */
  data: Prisma.XOR<Prisma.SessionPairHistoryUpdateInput, Prisma.SessionPairHistoryUncheckedUpdateInput>
  /**
   * Choose, which SessionPairHistory to update.
   */
  where: Prisma.SessionPairHistoryWhereUniqueInput
}

/**
 * SessionPairHistory updateMany
 */
export type SessionPairHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SessionPairHistories.
   */
  data: Prisma.XOR<Prisma.SessionPairHistoryUpdateManyMutationInput, Prisma.SessionPairHistoryUncheckedUpdateManyInput>
  /**
   * Filter which SessionPairHistories to update
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * Limit how many SessionPairHistories to update.
   */
  limit?: number
}

/**
 * SessionPairHistory updateManyAndReturn
 */
export type SessionPairHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * The data used to update SessionPairHistories.
   */
  data: Prisma.XOR<Prisma.SessionPairHistoryUpdateManyMutationInput, Prisma.SessionPairHistoryUncheckedUpdateManyInput>
  /**
   * Filter which SessionPairHistories to update
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * Limit how many SessionPairHistories to update.
   */
  limit?: number
}

/**
 * SessionPairHistory upsert
 */
export type SessionPairHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * The filter to search for the SessionPairHistory to update in case it exists.
   */
  where: Prisma.SessionPairHistoryWhereUniqueInput
  /**
   * In case the SessionPairHistory found by the `where` argument doesn't exist, create a new SessionPairHistory with this data.
   */
  create: Prisma.XOR<Prisma.SessionPairHistoryCreateInput, Prisma.SessionPairHistoryUncheckedCreateInput>
  /**
   * In case the SessionPairHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionPairHistoryUpdateInput, Prisma.SessionPairHistoryUncheckedUpdateInput>
}

/**
 * SessionPairHistory delete
 */
export type SessionPairHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
  /**
   * Filter which SessionPairHistory to delete.
   */
  where: Prisma.SessionPairHistoryWhereUniqueInput
}

/**
 * SessionPairHistory deleteMany
 */
export type SessionPairHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SessionPairHistories to delete
   */
  where?: Prisma.SessionPairHistoryWhereInput
  /**
   * Limit how many SessionPairHistories to delete.
   */
  limit?: number
}

/**
 * SessionPairHistory without action
 */
export type SessionPairHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionPairHistory
   */
  select?: Prisma.SessionPairHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SessionPairHistory
   */
  omit?: Prisma.SessionPairHistoryOmit<ExtArgs> | null
}
