
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model AppConfig
 * 
 */
export type AppConfig = Prisma.AppConfigModel
/**
 * Model ClerkUser
 * *
 *  * ClerkUser is a direct mirror of authentication-level identities.
 *  * These records come directly from Clerk, synced via webhooks or getOrCreateUser().
 *  * It ensures that authentication data never interferes with application-level data.
 */
export type ClerkUser = Prisma.ClerkUserModel
/**
 * Model User
 * *
 *  * User is the core application-level identity.
 *  * All gameplay, teams, tournaments, and statistics are tied to this user.
 *  * Authentication data from ClerkUser is linked but not dependent.
 */
export type User = Prisma.UserModel
/**
 * Model Team
 * 
 */
export type Team = Prisma.TeamModel
/**
 * Model TeamMember
 * 
 */
export type TeamMember = Prisma.TeamMemberModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model SessionParticipant
 * 
 */
export type SessionParticipant = Prisma.SessionParticipantModel
/**
 * Model Game
 * 
 */
export type Game = Prisma.GameModel
/**
 * Model PairStat
 * 
 */
export type PairStat = Prisma.PairStatModel
/**
 * Model SessionPairHistory
 * *
 *  * ============================================================
 *  * TOURNAMENTS
 *  * ============================================================
 */
export type SessionPairHistory = Prisma.SessionPairHistoryModel
/**
 * Model SessionPlayerStats
 * 
 */
export type SessionPlayerStats = Prisma.SessionPlayerStatsModel
/**
 * Model Tournament
 * 
 */
export type Tournament = Prisma.TournamentModel
/**
 * Model TournamentMember
 * 
 */
export type TournamentMember = Prisma.TournamentMemberModel
/**
 * Model TournamentTeam
 * 
 */
export type TournamentTeam = Prisma.TournamentTeamModel
/**
 * Model TournamentGame
 * 
 */
export type TournamentGame = Prisma.TournamentGameModel
/**
 * Model MatchEvent
 * 
 */
export type MatchEvent = Prisma.MatchEventModel
/**
 * Model Stage
 * 
 */
export type Stage = Prisma.StageModel
/**
 * Model Payment
 * 
 */
export type Payment = Prisma.PaymentModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Activity
 * 
 */
export type Activity = Prisma.ActivityModel
/**
 * Model CalendarEvent
 * 
 */
export type CalendarEvent = Prisma.CalendarEventModel
/**
 * Model TournamentPlayer
 * 
 */
export type TournamentPlayer = Prisma.TournamentPlayerModel
/**
 * Model TournamentPoint
 * 
 */
export type TournamentPoint = Prisma.TournamentPointModel
/**
 * Model TournamentEnrollment
 * 
 */
export type TournamentEnrollment = Prisma.TournamentEnrollmentModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model VerificationToken
 * 
 */
export type VerificationToken = Prisma.VerificationTokenModel
