
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AppConfigScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClerkUserScalarFieldEnum = {
  id: 'id',
  clerkId: 'clerkId',
  email: 'email',
  fullName: 'fullName',
  imageUrl: 'imageUrl',
  lastSyncedAt: 'lastSyncedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  image: 'image',
  displayName: 'displayName',
  bio: 'bio',
  createdAt: 'createdAt',
  clerkUserId: 'clerkUserId',
  points: 'points',
  wins: 'wins',
  losses: 'losses',
  eloRating: 'eloRating',
  packageType: 'packageType',
  teamQuota: 'teamQuota',
  tournamentQuota: 'tournamentQuota',
  teamCount: 'teamCount',
  tournamentCount: 'tournamentCount',
  planExpiresAt: 'planExpiresAt'
};

exports.Prisma.TeamScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  ownerId: 'ownerId',
  createdAt: 'createdAt',
  gamesPlayed: 'gamesPlayed',
  gamesWon: 'gamesWon'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  userId: 'userId',
  displayName: 'displayName',
  email: 'email',
  role: 'role',
  joinedAt: 'joinedAt'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  teamId: 'teamId',
  name: 'name',
  date: 'date',
  createdAt: 'createdAt'
};

exports.Prisma.SessionParticipantScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  memberId: 'memberId',
  isSelected: 'isSelected'
};

exports.Prisma.GameScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  sessionId: 'sessionId',
  teamAPlayers: 'teamAPlayers',
  teamBPlayers: 'teamBPlayers',
  winner: 'winner',
  teamAScore: 'teamAScore',
  teamBScore: 'teamBScore',
  createdAt: 'createdAt'
};

exports.Prisma.PairStatScalarFieldEnum = {
  id: 'id',
  teamId: 'teamId',
  playerA: 'playerA',
  playerB: 'playerB',
  plays: 'plays',
  wins: 'wins'
};

exports.Prisma.SessionPairHistoryScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  playerA: 'playerA',
  playerB: 'playerB',
  createdAt: 'createdAt'
};

exports.Prisma.SessionPlayerStatsScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  player: 'player',
  plays: 'plays',
  totalPoints: 'totalPoints',
  pointDiff: 'pointDiff',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TournamentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  ownerId: 'ownerId',
  createdAt: 'createdAt',
  isActive: 'isActive',
  minGamesPerPlayer: 'minGamesPerPlayer',
  bannerUrl: 'bannerUrl',
  startDate: 'startDate',
  endDate: 'endDate',
  matchDays: 'matchDays',
  courts: 'courts',
  auctionPurse: 'auctionPurse',
  useCustomStats: 'useCustomStats',
  thumbnailUrl: 'thumbnailUrl',
  galleryImages: 'galleryImages',
  description: 'description',
  rules: 'rules',
  contactPhone: 'contactPhone',
  entryFee: 'entryFee',
  paymentUpi: 'paymentUpi',
  paymentQrCode: 'paymentQrCode',
  cashContactName: 'cashContactName',
  cashContactNumber: 'cashContactNumber'
};

exports.Prisma.TournamentMemberScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  userId: 'userId',
  role: 'role',
  createdAt: 'createdAt'
};

exports.Prisma.TournamentTeamScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  name: 'name',
  color: 'color',
  logoUrl: 'logoUrl',
  purseSpent: 'purseSpent',
  matchesPlayed: 'matchesPlayed',
  wins: 'wins',
  losses: 'losses',
  draws: 'draws',
  points: 'points',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TournamentGameScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  stageId: 'stageId',
  teamAId: 'teamAId',
  teamBId: 'teamBId',
  teamAPlayers: 'teamAPlayers',
  teamBPlayers: 'teamBPlayers',
  teamAScore: 'teamAScore',
  teamBScore: 'teamBScore',
  winningTeam: 'winningTeam',
  status: 'status',
  round: 'round',
  scheduleTime: 'scheduleTime',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  currentSet: 'currentSet'
};

exports.Prisma.MatchEventScalarFieldEnum = {
  id: 'id',
  gameId: 'gameId',
  type: 'type',
  playerId: 'playerId',
  timestamp: 'timestamp',
  scoreA: 'scoreA',
  scoreB: 'scoreB',
  metadata: 'metadata'
};

exports.Prisma.StageScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  name: 'name',
  order: 'order',
  createdAt: 'createdAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  amount: 'amount',
  currency: 'currency',
  referenceId: 'referenceId',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  message: 'message',
  isRead: 'isRead',
  link: 'link',
  createdAt: 'createdAt'
};

exports.Prisma.ActivityScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  refId: 'refId',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.CalendarEventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  startTime: 'startTime',
  endTime: 'endTime',
  location: 'location',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  createdAt: 'createdAt'
};

exports.Prisma.TournamentPlayerScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  teamId: 'teamId',
  userId: 'userId',
  name: 'name',
  email: 'email',
  soldPrice: 'soldPrice',
  isCaptain: 'isCaptain',
  matchesPlayed: 'matchesPlayed',
  isCheckedIn: 'isCheckedIn',
  checkInTime: 'checkInTime',
  customRating: 'customRating',
  customMatches: 'customMatches',
  customWins: 'customWins',
  createdAt: 'createdAt'
};

exports.Prisma.TournamentPointScalarFieldEnum = {
  id: 'id',
  gameId: 'gameId',
  scorerId: 'scorerId',
  pointType: 'pointType',
  timestamp: 'timestamp',
  tournamentTeamId: 'tournamentTeamId'
};

exports.Prisma.TournamentEnrollmentScalarFieldEnum = {
  id: 'id',
  tournamentId: 'tournamentId',
  userId: 'userId',
  name: 'name',
  email: 'email',
  mobile: 'mobile',
  paymentMode: 'paymentMode',
  paymentScreenshotUrl: 'paymentScreenshotUrl',
  transactionId: 'transactionId',
  status: 'status',
  adminNotes: 'adminNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailLogScalarFieldEnum = {
  id: 'id',
  recipient: 'recipient',
  subject: 'subject',
  body: 'body',
  status: 'status',
  error: 'error',
  createdAt: 'createdAt',
  sentAt: 'sentAt'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.PackageType = exports.$Enums.PackageType = {
  FREE: 'FREE',
  TEAM_PACKAGE: 'TEAM_PACKAGE',
  TOURNAMENT_PACKAGE: 'TOURNAMENT_PACKAGE',
  PRO_PACKAGE: 'PRO_PACKAGE'
};

exports.Role = exports.$Enums.Role = {
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER'
};

exports.TournamentRole = exports.$Enums.TournamentRole = {
  MANAGER: 'MANAGER',
  CO_OWNER: 'CO_OWNER',
  REFEREE: 'REFEREE',
  AUCTIONEER: 'AUCTIONEER',
  TEAM_OWNER: 'TEAM_OWNER',
  PLAYER: 'PLAYER'
};

exports.WinningTeam = exports.$Enums.WinningTeam = {
  A: 'A',
  B: 'B',
  DRAW: 'DRAW'
};

exports.GameStatus = exports.$Enums.GameStatus = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

exports.EventType = exports.$Enums.EventType = {
  POINT_SCORED: 'POINT_SCORED',
  FAULT: 'FAULT',
  TIMEOUT: 'TIMEOUT',
  GAME_START: 'GAME_START',
  GAME_END: 'GAME_END',
  UNDO: 'UNDO'
};

exports.PaymentType = exports.$Enums.PaymentType = {
  TEAM_PURCHASE: 'TEAM_PURCHASE',
  TOURNAMENT_PURCHASE: 'TOURNAMENT_PURCHASE',
  PACKAGE_SUBSCRIPTION: 'PACKAGE_SUBSCRIPTION',
  MANUAL_CREDIT: 'MANUAL_CREDIT'
};

exports.ActivityType = exports.$Enums.ActivityType = {
  TEAM_CREATED: 'TEAM_CREATED',
  TOURNAMENT_CREATED: 'TOURNAMENT_CREATED',
  GAME_PLAYED: 'GAME_PLAYED',
  GAME_WON: 'GAME_WON',
  MEMBER_ADDED: 'MEMBER_ADDED',
  PAYMENT_MADE: 'PAYMENT_MADE'
};

exports.PaymentMode = exports.$Enums.PaymentMode = {
  ONLINE: 'ONLINE',
  CASH: 'CASH'
};

exports.EnrollmentStatus = exports.$Enums.EnrollmentStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.Prisma.ModelName = {
  AppConfig: 'AppConfig',
  ClerkUser: 'ClerkUser',
  User: 'User',
  Team: 'Team',
  TeamMember: 'TeamMember',
  Session: 'Session',
  SessionParticipant: 'SessionParticipant',
  Game: 'Game',
  PairStat: 'PairStat',
  SessionPairHistory: 'SessionPairHistory',
  SessionPlayerStats: 'SessionPlayerStats',
  Tournament: 'Tournament',
  TournamentMember: 'TournamentMember',
  TournamentTeam: 'TournamentTeam',
  TournamentGame: 'TournamentGame',
  MatchEvent: 'MatchEvent',
  Stage: 'Stage',
  Payment: 'Payment',
  Notification: 'Notification',
  Activity: 'Activity',
  CalendarEvent: 'CalendarEvent',
  TournamentPlayer: 'TournamentPlayer',
  TournamentPoint: 'TournamentPoint',
  TournamentEnrollment: 'TournamentEnrollment',
  EmailLog: 'EmailLog',
  VerificationToken: 'VerificationToken'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
