
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PairStat` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PairStat
 * 
 */
export type PairStatModel = runtime.Types.Result.DefaultSelection<Prisma.$PairStatPayload>

export type AggregatePairStat = {
  _count: PairStatCountAggregateOutputType | null
  _avg: PairStatAvgAggregateOutputType | null
  _sum: PairStatSumAggregateOutputType | null
  _min: PairStatMinAggregateOutputType | null
  _max: PairStatMaxAggregateOutputType | null
}

export type PairStatAvgAggregateOutputType = {
  plays: number | null
  wins: number | null
}

export type PairStatSumAggregateOutputType = {
  plays: number | null
  wins: number | null
}

export type PairStatMinAggregateOutputType = {
  id: string | null
  teamId: string | null
  playerA: string | null
  playerB: string | null
  plays: number | null
  wins: number | null
}

export type PairStatMaxAggregateOutputType = {
  id: string | null
  teamId: string | null
  playerA: string | null
  playerB: string | null
  plays: number | null
  wins: number | null
}

export type PairStatCountAggregateOutputType = {
  id: number
  teamId: number
  playerA: number
  playerB: number
  plays: number
  wins: number
  _all: number
}


export type PairStatAvgAggregateInputType = {
  plays?: true
  wins?: true
}

export type PairStatSumAggregateInputType = {
  plays?: true
  wins?: true
}

export type PairStatMinAggregateInputType = {
  id?: true
  teamId?: true
  playerA?: true
  playerB?: true
  plays?: true
  wins?: true
}

export type PairStatMaxAggregateInputType = {
  id?: true
  teamId?: true
  playerA?: true
  playerB?: true
  plays?: true
  wins?: true
}

export type PairStatCountAggregateInputType = {
  id?: true
  teamId?: true
  playerA?: true
  playerB?: true
  plays?: true
  wins?: true
  _all?: true
}

export type PairStatAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PairStat to aggregate.
   */
  where?: Prisma.PairStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PairStats to fetch.
   */
  orderBy?: Prisma.PairStatOrderByWithRelationInput | Prisma.PairStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PairStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PairStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PairStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PairStats
  **/
  _count?: true | PairStatCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PairStatAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PairStatSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PairStatMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PairStatMaxAggregateInputType
}

export type GetPairStatAggregateType<T extends PairStatAggregateArgs> = {
      [P in keyof T & keyof AggregatePairStat]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePairStat[P]>
    : Prisma.GetScalarType<T[P], AggregatePairStat[P]>
}




export type PairStatGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PairStatWhereInput
  orderBy?: Prisma.PairStatOrderByWithAggregationInput | Prisma.PairStatOrderByWithAggregationInput[]
  by: Prisma.PairStatScalarFieldEnum[] | Prisma.PairStatScalarFieldEnum
  having?: Prisma.PairStatScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PairStatCountAggregateInputType | true
  _avg?: PairStatAvgAggregateInputType
  _sum?: PairStatSumAggregateInputType
  _min?: PairStatMinAggregateInputType
  _max?: PairStatMaxAggregateInputType
}

export type PairStatGroupByOutputType = {
  id: string
  teamId: string
  playerA: string
  playerB: string
  plays: number
  wins: number
  _count: PairStatCountAggregateOutputType | null
  _avg: PairStatAvgAggregateOutputType | null
  _sum: PairStatSumAggregateOutputType | null
  _min: PairStatMinAggregateOutputType | null
  _max: PairStatMaxAggregateOutputType | null
}

type GetPairStatGroupByPayload<T extends PairStatGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PairStatGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PairStatGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PairStatGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PairStatGroupByOutputType[P]>
      }
    >
  >



export type PairStatWhereInput = {
  AND?: Prisma.PairStatWhereInput | Prisma.PairStatWhereInput[]
  OR?: Prisma.PairStatWhereInput[]
  NOT?: Prisma.PairStatWhereInput | Prisma.PairStatWhereInput[]
  id?: Prisma.StringFilter<"PairStat"> | string
  teamId?: Prisma.StringFilter<"PairStat"> | string
  playerA?: Prisma.StringFilter<"PairStat"> | string
  playerB?: Prisma.StringFilter<"PairStat"> | string
  plays?: Prisma.IntFilter<"PairStat"> | number
  wins?: Prisma.IntFilter<"PairStat"> | number
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}

export type PairStatOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  team?: Prisma.TeamOrderByWithRelationInput
}

export type PairStatWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  teamId_playerA_playerB?: Prisma.PairStatTeamIdPlayerAPlayerBCompoundUniqueInput
  AND?: Prisma.PairStatWhereInput | Prisma.PairStatWhereInput[]
  OR?: Prisma.PairStatWhereInput[]
  NOT?: Prisma.PairStatWhereInput | Prisma.PairStatWhereInput[]
  teamId?: Prisma.StringFilter<"PairStat"> | string
  playerA?: Prisma.StringFilter<"PairStat"> | string
  playerB?: Prisma.StringFilter<"PairStat"> | string
  plays?: Prisma.IntFilter<"PairStat"> | number
  wins?: Prisma.IntFilter<"PairStat"> | number
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}, "id" | "teamId_playerA_playerB">

export type PairStatOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  _count?: Prisma.PairStatCountOrderByAggregateInput
  _avg?: Prisma.PairStatAvgOrderByAggregateInput
  _max?: Prisma.PairStatMaxOrderByAggregateInput
  _min?: Prisma.PairStatMinOrderByAggregateInput
  _sum?: Prisma.PairStatSumOrderByAggregateInput
}

export type PairStatScalarWhereWithAggregatesInput = {
  AND?: Prisma.PairStatScalarWhereWithAggregatesInput | Prisma.PairStatScalarWhereWithAggregatesInput[]
  OR?: Prisma.PairStatScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PairStatScalarWhereWithAggregatesInput | Prisma.PairStatScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PairStat"> | string
  teamId?: Prisma.StringWithAggregatesFilter<"PairStat"> | string
  playerA?: Prisma.StringWithAggregatesFilter<"PairStat"> | string
  playerB?: Prisma.StringWithAggregatesFilter<"PairStat"> | string
  plays?: Prisma.IntWithAggregatesFilter<"PairStat"> | number
  wins?: Prisma.IntWithAggregatesFilter<"PairStat"> | number
}

export type PairStatCreateInput = {
  id?: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
  team: Prisma.TeamCreateNestedOneWithoutPairStatsInput
}

export type PairStatUncheckedCreateInput = {
  id?: string
  teamId: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
}

export type PairStatUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  team?: Prisma.TeamUpdateOneRequiredWithoutPairStatsNestedInput
}

export type PairStatUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PairStatCreateManyInput = {
  id?: string
  teamId: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
}

export type PairStatUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PairStatUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  teamId?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PairStatListRelationFilter = {
  every?: Prisma.PairStatWhereInput
  some?: Prisma.PairStatWhereInput
  none?: Prisma.PairStatWhereInput
}

export type PairStatOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PairStatTeamIdPlayerAPlayerBCompoundUniqueInput = {
  teamId: string
  playerA: string
  playerB: string
}

export type PairStatCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
}

export type PairStatAvgOrderByAggregateInput = {
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
}

export type PairStatMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
}

export type PairStatMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  teamId?: Prisma.SortOrder
  playerA?: Prisma.SortOrder
  playerB?: Prisma.SortOrder
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
}

export type PairStatSumOrderByAggregateInput = {
  plays?: Prisma.SortOrder
  wins?: Prisma.SortOrder
}

export type PairStatCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput> | Prisma.PairStatCreateWithoutTeamInput[] | Prisma.PairStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.PairStatCreateOrConnectWithoutTeamInput | Prisma.PairStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.PairStatCreateManyTeamInputEnvelope
  connect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
}

export type PairStatUncheckedCreateNestedManyWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput> | Prisma.PairStatCreateWithoutTeamInput[] | Prisma.PairStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.PairStatCreateOrConnectWithoutTeamInput | Prisma.PairStatCreateOrConnectWithoutTeamInput[]
  createMany?: Prisma.PairStatCreateManyTeamInputEnvelope
  connect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
}

export type PairStatUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput> | Prisma.PairStatCreateWithoutTeamInput[] | Prisma.PairStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.PairStatCreateOrConnectWithoutTeamInput | Prisma.PairStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.PairStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.PairStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.PairStatCreateManyTeamInputEnvelope
  set?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  disconnect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  delete?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  connect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  update?: Prisma.PairStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.PairStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.PairStatUpdateManyWithWhereWithoutTeamInput | Prisma.PairStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.PairStatScalarWhereInput | Prisma.PairStatScalarWhereInput[]
}

export type PairStatUncheckedUpdateManyWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput> | Prisma.PairStatCreateWithoutTeamInput[] | Prisma.PairStatUncheckedCreateWithoutTeamInput[]
  connectOrCreate?: Prisma.PairStatCreateOrConnectWithoutTeamInput | Prisma.PairStatCreateOrConnectWithoutTeamInput[]
  upsert?: Prisma.PairStatUpsertWithWhereUniqueWithoutTeamInput | Prisma.PairStatUpsertWithWhereUniqueWithoutTeamInput[]
  createMany?: Prisma.PairStatCreateManyTeamInputEnvelope
  set?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  disconnect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  delete?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  connect?: Prisma.PairStatWhereUniqueInput | Prisma.PairStatWhereUniqueInput[]
  update?: Prisma.PairStatUpdateWithWhereUniqueWithoutTeamInput | Prisma.PairStatUpdateWithWhereUniqueWithoutTeamInput[]
  updateMany?: Prisma.PairStatUpdateManyWithWhereWithoutTeamInput | Prisma.PairStatUpdateManyWithWhereWithoutTeamInput[]
  deleteMany?: Prisma.PairStatScalarWhereInput | Prisma.PairStatScalarWhereInput[]
}

export type PairStatCreateWithoutTeamInput = {
  id?: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
}

export type PairStatUncheckedCreateWithoutTeamInput = {
  id?: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
}

export type PairStatCreateOrConnectWithoutTeamInput = {
  where: Prisma.PairStatWhereUniqueInput
  create: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput>
}

export type PairStatCreateManyTeamInputEnvelope = {
  data: Prisma.PairStatCreateManyTeamInput | Prisma.PairStatCreateManyTeamInput[]
  skipDuplicates?: boolean
}

export type PairStatUpsertWithWhereUniqueWithoutTeamInput = {
  where: Prisma.PairStatWhereUniqueInput
  update: Prisma.XOR<Prisma.PairStatUpdateWithoutTeamInput, Prisma.PairStatUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.PairStatCreateWithoutTeamInput, Prisma.PairStatUncheckedCreateWithoutTeamInput>
}

export type PairStatUpdateWithWhereUniqueWithoutTeamInput = {
  where: Prisma.PairStatWhereUniqueInput
  data: Prisma.XOR<Prisma.PairStatUpdateWithoutTeamInput, Prisma.PairStatUncheckedUpdateWithoutTeamInput>
}

export type PairStatUpdateManyWithWhereWithoutTeamInput = {
  where: Prisma.PairStatScalarWhereInput
  data: Prisma.XOR<Prisma.PairStatUpdateManyMutationInput, Prisma.PairStatUncheckedUpdateManyWithoutTeamInput>
}

export type PairStatScalarWhereInput = {
  AND?: Prisma.PairStatScalarWhereInput | Prisma.PairStatScalarWhereInput[]
  OR?: Prisma.PairStatScalarWhereInput[]
  NOT?: Prisma.PairStatScalarWhereInput | Prisma.PairStatScalarWhereInput[]
  id?: Prisma.StringFilter<"PairStat"> | string
  teamId?: Prisma.StringFilter<"PairStat"> | string
  playerA?: Prisma.StringFilter<"PairStat"> | string
  playerB?: Prisma.StringFilter<"PairStat"> | string
  plays?: Prisma.IntFilter<"PairStat"> | number
  wins?: Prisma.IntFilter<"PairStat"> | number
}

export type PairStatCreateManyTeamInput = {
  id?: string
  playerA: string
  playerB: string
  plays?: number
  wins?: number
}

export type PairStatUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PairStatUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PairStatUncheckedUpdateManyWithoutTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playerA?: Prisma.StringFieldUpdateOperationsInput | string
  playerB?: Prisma.StringFieldUpdateOperationsInput | string
  plays?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
}



export type PairStatSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  playerA?: boolean
  playerB?: boolean
  plays?: boolean
  wins?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pairStat"]>

export type PairStatSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  playerA?: boolean
  playerB?: boolean
  plays?: boolean
  wins?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pairStat"]>

export type PairStatSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  teamId?: boolean
  playerA?: boolean
  playerB?: boolean
  plays?: boolean
  wins?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pairStat"]>

export type PairStatSelectScalar = {
  id?: boolean
  teamId?: boolean
  playerA?: boolean
  playerB?: boolean
  plays?: boolean
  wins?: boolean
}

export type PairStatOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "teamId" | "playerA" | "playerB" | "plays" | "wins", ExtArgs["result"]["pairStat"]>
export type PairStatInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type PairStatIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type PairStatIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}

export type $PairStatPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PairStat"
  objects: {
    team: Prisma.$TeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    teamId: string
    playerA: string
    playerB: string
    plays: number
    wins: number
  }, ExtArgs["result"]["pairStat"]>
  composites: {}
}

export type PairStatGetPayload<S extends boolean | null | undefined | PairStatDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PairStatPayload, S>

export type PairStatCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PairStatFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PairStatCountAggregateInputType | true
  }

export interface PairStatDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PairStat'], meta: { name: 'PairStat' } }
  /**
   * Find zero or one PairStat that matches the filter.
   * @param {PairStatFindUniqueArgs} args - Arguments to find a PairStat
   * @example
   * // Get one PairStat
   * const pairStat = await prisma.pairStat.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PairStatFindUniqueArgs>(args: Prisma.SelectSubset<T, PairStatFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PairStat that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PairStatFindUniqueOrThrowArgs} args - Arguments to find a PairStat
   * @example
   * // Get one PairStat
   * const pairStat = await prisma.pairStat.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PairStatFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PairStatFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PairStat that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatFindFirstArgs} args - Arguments to find a PairStat
   * @example
   * // Get one PairStat
   * const pairStat = await prisma.pairStat.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PairStatFindFirstArgs>(args?: Prisma.SelectSubset<T, PairStatFindFirstArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PairStat that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatFindFirstOrThrowArgs} args - Arguments to find a PairStat
   * @example
   * // Get one PairStat
   * const pairStat = await prisma.pairStat.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PairStatFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PairStatFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PairStats that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PairStats
   * const pairStats = await prisma.pairStat.findMany()
   * 
   * // Get first 10 PairStats
   * const pairStats = await prisma.pairStat.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pairStatWithIdOnly = await prisma.pairStat.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PairStatFindManyArgs>(args?: Prisma.SelectSubset<T, PairStatFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PairStat.
   * @param {PairStatCreateArgs} args - Arguments to create a PairStat.
   * @example
   * // Create one PairStat
   * const PairStat = await prisma.pairStat.create({
   *   data: {
   *     // ... data to create a PairStat
   *   }
   * })
   * 
   */
  create<T extends PairStatCreateArgs>(args: Prisma.SelectSubset<T, PairStatCreateArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PairStats.
   * @param {PairStatCreateManyArgs} args - Arguments to create many PairStats.
   * @example
   * // Create many PairStats
   * const pairStat = await prisma.pairStat.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PairStatCreateManyArgs>(args?: Prisma.SelectSubset<T, PairStatCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PairStats and returns the data saved in the database.
   * @param {PairStatCreateManyAndReturnArgs} args - Arguments to create many PairStats.
   * @example
   * // Create many PairStats
   * const pairStat = await prisma.pairStat.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PairStats and only return the `id`
   * const pairStatWithIdOnly = await prisma.pairStat.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PairStatCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PairStatCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PairStat.
   * @param {PairStatDeleteArgs} args - Arguments to delete one PairStat.
   * @example
   * // Delete one PairStat
   * const PairStat = await prisma.pairStat.delete({
   *   where: {
   *     // ... filter to delete one PairStat
   *   }
   * })
   * 
   */
  delete<T extends PairStatDeleteArgs>(args: Prisma.SelectSubset<T, PairStatDeleteArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PairStat.
   * @param {PairStatUpdateArgs} args - Arguments to update one PairStat.
   * @example
   * // Update one PairStat
   * const pairStat = await prisma.pairStat.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PairStatUpdateArgs>(args: Prisma.SelectSubset<T, PairStatUpdateArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PairStats.
   * @param {PairStatDeleteManyArgs} args - Arguments to filter PairStats to delete.
   * @example
   * // Delete a few PairStats
   * const { count } = await prisma.pairStat.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PairStatDeleteManyArgs>(args?: Prisma.SelectSubset<T, PairStatDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PairStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PairStats
   * const pairStat = await prisma.pairStat.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PairStatUpdateManyArgs>(args: Prisma.SelectSubset<T, PairStatUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PairStats and returns the data updated in the database.
   * @param {PairStatUpdateManyAndReturnArgs} args - Arguments to update many PairStats.
   * @example
   * // Update many PairStats
   * const pairStat = await prisma.pairStat.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PairStats and only return the `id`
   * const pairStatWithIdOnly = await prisma.pairStat.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PairStatUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PairStatUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PairStat.
   * @param {PairStatUpsertArgs} args - Arguments to update or create a PairStat.
   * @example
   * // Update or create a PairStat
   * const pairStat = await prisma.pairStat.upsert({
   *   create: {
   *     // ... data to create a PairStat
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PairStat we want to update
   *   }
   * })
   */
  upsert<T extends PairStatUpsertArgs>(args: Prisma.SelectSubset<T, PairStatUpsertArgs<ExtArgs>>): Prisma.Prisma__PairStatClient<runtime.Types.Result.GetResult<Prisma.$PairStatPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PairStats.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatCountArgs} args - Arguments to filter PairStats to count.
   * @example
   * // Count the number of PairStats
   * const count = await prisma.pairStat.count({
   *   where: {
   *     // ... the filter for the PairStats we want to count
   *   }
   * })
  **/
  count<T extends PairStatCountArgs>(
    args?: Prisma.Subset<T, PairStatCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PairStatCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PairStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PairStatAggregateArgs>(args: Prisma.Subset<T, PairStatAggregateArgs>): Prisma.PrismaPromise<GetPairStatAggregateType<T>>

  /**
   * Group by PairStat.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PairStatGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PairStatGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PairStatGroupByArgs['orderBy'] }
      : { orderBy?: PairStatGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PairStatGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPairStatGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PairStat model
 */
readonly fields: PairStatFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PairStat.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PairStatClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PairStat model
 */
export interface PairStatFieldRefs {
  readonly id: Prisma.FieldRef<"PairStat", 'String'>
  readonly teamId: Prisma.FieldRef<"PairStat", 'String'>
  readonly playerA: Prisma.FieldRef<"PairStat", 'String'>
  readonly playerB: Prisma.FieldRef<"PairStat", 'String'>
  readonly plays: Prisma.FieldRef<"PairStat", 'Int'>
  readonly wins: Prisma.FieldRef<"PairStat", 'Int'>
}
    

// Custom InputTypes
/**
 * PairStat findUnique
 */
export type PairStatFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter, which PairStat to fetch.
   */
  where: Prisma.PairStatWhereUniqueInput
}

/**
 * PairStat findUniqueOrThrow
 */
export type PairStatFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter, which PairStat to fetch.
   */
  where: Prisma.PairStatWhereUniqueInput
}

/**
 * PairStat findFirst
 */
export type PairStatFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter, which PairStat to fetch.
   */
  where?: Prisma.PairStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PairStats to fetch.
   */
  orderBy?: Prisma.PairStatOrderByWithRelationInput | Prisma.PairStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PairStats.
   */
  cursor?: Prisma.PairStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PairStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PairStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PairStats.
   */
  distinct?: Prisma.PairStatScalarFieldEnum | Prisma.PairStatScalarFieldEnum[]
}

/**
 * PairStat findFirstOrThrow
 */
export type PairStatFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter, which PairStat to fetch.
   */
  where?: Prisma.PairStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PairStats to fetch.
   */
  orderBy?: Prisma.PairStatOrderByWithRelationInput | Prisma.PairStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PairStats.
   */
  cursor?: Prisma.PairStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PairStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PairStats.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PairStats.
   */
  distinct?: Prisma.PairStatScalarFieldEnum | Prisma.PairStatScalarFieldEnum[]
}

/**
 * PairStat findMany
 */
export type PairStatFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter, which PairStats to fetch.
   */
  where?: Prisma.PairStatWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PairStats to fetch.
   */
  orderBy?: Prisma.PairStatOrderByWithRelationInput | Prisma.PairStatOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PairStats.
   */
  cursor?: Prisma.PairStatWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PairStats from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PairStats.
   */
  skip?: number
  distinct?: Prisma.PairStatScalarFieldEnum | Prisma.PairStatScalarFieldEnum[]
}

/**
 * PairStat create
 */
export type PairStatCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * The data needed to create a PairStat.
   */
  data: Prisma.XOR<Prisma.PairStatCreateInput, Prisma.PairStatUncheckedCreateInput>
}

/**
 * PairStat createMany
 */
export type PairStatCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PairStats.
   */
  data: Prisma.PairStatCreateManyInput | Prisma.PairStatCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PairStat createManyAndReturn
 */
export type PairStatCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * The data used to create many PairStats.
   */
  data: Prisma.PairStatCreateManyInput | Prisma.PairStatCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PairStat update
 */
export type PairStatUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * The data needed to update a PairStat.
   */
  data: Prisma.XOR<Prisma.PairStatUpdateInput, Prisma.PairStatUncheckedUpdateInput>
  /**
   * Choose, which PairStat to update.
   */
  where: Prisma.PairStatWhereUniqueInput
}

/**
 * PairStat updateMany
 */
export type PairStatUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PairStats.
   */
  data: Prisma.XOR<Prisma.PairStatUpdateManyMutationInput, Prisma.PairStatUncheckedUpdateManyInput>
  /**
   * Filter which PairStats to update
   */
  where?: Prisma.PairStatWhereInput
  /**
   * Limit how many PairStats to update.
   */
  limit?: number
}

/**
 * PairStat updateManyAndReturn
 */
export type PairStatUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * The data used to update PairStats.
   */
  data: Prisma.XOR<Prisma.PairStatUpdateManyMutationInput, Prisma.PairStatUncheckedUpdateManyInput>
  /**
   * Filter which PairStats to update
   */
  where?: Prisma.PairStatWhereInput
  /**
   * Limit how many PairStats to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PairStat upsert
 */
export type PairStatUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * The filter to search for the PairStat to update in case it exists.
   */
  where: Prisma.PairStatWhereUniqueInput
  /**
   * In case the PairStat found by the `where` argument doesn't exist, create a new PairStat with this data.
   */
  create: Prisma.XOR<Prisma.PairStatCreateInput, Prisma.PairStatUncheckedCreateInput>
  /**
   * In case the PairStat was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PairStatUpdateInput, Prisma.PairStatUncheckedUpdateInput>
}

/**
 * PairStat delete
 */
export type PairStatDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
  /**
   * Filter which PairStat to delete.
   */
  where: Prisma.PairStatWhereUniqueInput
}

/**
 * PairStat deleteMany
 */
export type PairStatDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PairStats to delete
   */
  where?: Prisma.PairStatWhereInput
  /**
   * Limit how many PairStats to delete.
   */
  limit?: number
}

/**
 * PairStat without action
 */
export type PairStatDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PairStat
   */
  select?: Prisma.PairStatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PairStat
   */
  omit?: Prisma.PairStatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PairStatInclude<ExtArgs> | null
}
