
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentPoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentPoint
 * 
 */
export type TournamentPointModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentPointPayload>

export type AggregateTournamentPoint = {
  _count: TournamentPointCountAggregateOutputType | null
  _min: TournamentPointMinAggregateOutputType | null
  _max: TournamentPointMaxAggregateOutputType | null
}

export type TournamentPointMinAggregateOutputType = {
  id: string | null
  gameId: string | null
  scorerId: string | null
  pointType: string | null
  timestamp: Date | null
  tournamentTeamId: string | null
}

export type TournamentPointMaxAggregateOutputType = {
  id: string | null
  gameId: string | null
  scorerId: string | null
  pointType: string | null
  timestamp: Date | null
  tournamentTeamId: string | null
}

export type TournamentPointCountAggregateOutputType = {
  id: number
  gameId: number
  scorerId: number
  pointType: number
  timestamp: number
  tournamentTeamId: number
  _all: number
}


export type TournamentPointMinAggregateInputType = {
  id?: true
  gameId?: true
  scorerId?: true
  pointType?: true
  timestamp?: true
  tournamentTeamId?: true
}

export type TournamentPointMaxAggregateInputType = {
  id?: true
  gameId?: true
  scorerId?: true
  pointType?: true
  timestamp?: true
  tournamentTeamId?: true
}

export type TournamentPointCountAggregateInputType = {
  id?: true
  gameId?: true
  scorerId?: true
  pointType?: true
  timestamp?: true
  tournamentTeamId?: true
  _all?: true
}

export type TournamentPointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentPoint to aggregate.
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPoints to fetch.
   */
  orderBy?: Prisma.TournamentPointOrderByWithRelationInput | Prisma.TournamentPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentPoints
  **/
  _count?: true | TournamentPointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentPointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentPointMaxAggregateInputType
}

export type GetTournamentPointAggregateType<T extends TournamentPointAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentPoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentPoint[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentPoint[P]>
}




export type TournamentPointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentPointWhereInput
  orderBy?: Prisma.TournamentPointOrderByWithAggregationInput | Prisma.TournamentPointOrderByWithAggregationInput[]
  by: Prisma.TournamentPointScalarFieldEnum[] | Prisma.TournamentPointScalarFieldEnum
  having?: Prisma.TournamentPointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentPointCountAggregateInputType | true
  _min?: TournamentPointMinAggregateInputType
  _max?: TournamentPointMaxAggregateInputType
}

export type TournamentPointGroupByOutputType = {
  id: string
  gameId: string
  scorerId: string | null
  pointType: string | null
  timestamp: Date
  tournamentTeamId: string | null
  _count: TournamentPointCountAggregateOutputType | null
  _min: TournamentPointMinAggregateOutputType | null
  _max: TournamentPointMaxAggregateOutputType | null
}

type GetTournamentPointGroupByPayload<T extends TournamentPointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentPointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentPointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentPointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentPointGroupByOutputType[P]>
      }
    >
  >



export type TournamentPointWhereInput = {
  AND?: Prisma.TournamentPointWhereInput | Prisma.TournamentPointWhereInput[]
  OR?: Prisma.TournamentPointWhereInput[]
  NOT?: Prisma.TournamentPointWhereInput | Prisma.TournamentPointWhereInput[]
  id?: Prisma.StringFilter<"TournamentPoint"> | string
  gameId?: Prisma.StringFilter<"TournamentPoint"> | string
  scorerId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  pointType?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  timestamp?: Prisma.DateTimeFilter<"TournamentPoint"> | Date | string
  tournamentTeamId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  game?: Prisma.XOR<Prisma.TournamentGameScalarRelationFilter, Prisma.TournamentGameWhereInput>
  scorer?: Prisma.XOR<Prisma.TournamentPlayerNullableScalarRelationFilter, Prisma.TournamentPlayerWhereInput> | null
  tournamentTeam?: Prisma.XOR<Prisma.TournamentTeamNullableScalarRelationFilter, Prisma.TournamentTeamWhereInput> | null
}

export type TournamentPointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  scorerId?: Prisma.SortOrderInput | Prisma.SortOrder
  pointType?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  tournamentTeamId?: Prisma.SortOrderInput | Prisma.SortOrder
  game?: Prisma.TournamentGameOrderByWithRelationInput
  scorer?: Prisma.TournamentPlayerOrderByWithRelationInput
  tournamentTeam?: Prisma.TournamentTeamOrderByWithRelationInput
}

export type TournamentPointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TournamentPointWhereInput | Prisma.TournamentPointWhereInput[]
  OR?: Prisma.TournamentPointWhereInput[]
  NOT?: Prisma.TournamentPointWhereInput | Prisma.TournamentPointWhereInput[]
  gameId?: Prisma.StringFilter<"TournamentPoint"> | string
  scorerId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  pointType?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  timestamp?: Prisma.DateTimeFilter<"TournamentPoint"> | Date | string
  tournamentTeamId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  game?: Prisma.XOR<Prisma.TournamentGameScalarRelationFilter, Prisma.TournamentGameWhereInput>
  scorer?: Prisma.XOR<Prisma.TournamentPlayerNullableScalarRelationFilter, Prisma.TournamentPlayerWhereInput> | null
  tournamentTeam?: Prisma.XOR<Prisma.TournamentTeamNullableScalarRelationFilter, Prisma.TournamentTeamWhereInput> | null
}, "id">

export type TournamentPointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  scorerId?: Prisma.SortOrderInput | Prisma.SortOrder
  pointType?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  tournamentTeamId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TournamentPointCountOrderByAggregateInput
  _max?: Prisma.TournamentPointMaxOrderByAggregateInput
  _min?: Prisma.TournamentPointMinOrderByAggregateInput
}

export type TournamentPointScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentPointScalarWhereWithAggregatesInput | Prisma.TournamentPointScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentPointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentPointScalarWhereWithAggregatesInput | Prisma.TournamentPointScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentPoint"> | string
  gameId?: Prisma.StringWithAggregatesFilter<"TournamentPoint"> | string
  scorerId?: Prisma.StringNullableWithAggregatesFilter<"TournamentPoint"> | string | null
  pointType?: Prisma.StringNullableWithAggregatesFilter<"TournamentPoint"> | string | null
  timestamp?: Prisma.DateTimeWithAggregatesFilter<"TournamentPoint"> | Date | string
  tournamentTeamId?: Prisma.StringNullableWithAggregatesFilter<"TournamentPoint"> | string | null
}

export type TournamentPointCreateInput = {
  id?: string
  pointType?: string | null
  timestamp?: Date | string
  game: Prisma.TournamentGameCreateNestedOneWithoutTournamentPointsInput
  scorer?: Prisma.TournamentPlayerCreateNestedOneWithoutScoredPointsInput
  tournamentTeam?: Prisma.TournamentTeamCreateNestedOneWithoutPointsLogInput
}

export type TournamentPointUncheckedCreateInput = {
  id?: string
  gameId: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  game?: Prisma.TournamentGameUpdateOneRequiredWithoutTournamentPointsNestedInput
  scorer?: Prisma.TournamentPlayerUpdateOneWithoutScoredPointsNestedInput
  tournamentTeam?: Prisma.TournamentTeamUpdateOneWithoutPointsLogNestedInput
}

export type TournamentPointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TournamentPointCreateManyInput = {
  id?: string
  gameId: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TournamentPointListRelationFilter = {
  every?: Prisma.TournamentPointWhereInput
  some?: Prisma.TournamentPointWhereInput
  none?: Prisma.TournamentPointWhereInput
}

export type TournamentPointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentPointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  scorerId?: Prisma.SortOrder
  pointType?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  tournamentTeamId?: Prisma.SortOrder
}

export type TournamentPointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  scorerId?: Prisma.SortOrder
  pointType?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  tournamentTeamId?: Prisma.SortOrder
}

export type TournamentPointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  scorerId?: Prisma.SortOrder
  pointType?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  tournamentTeamId?: Prisma.SortOrder
}

export type TournamentPointCreateNestedManyWithoutTournamentTeamInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput> | Prisma.TournamentPointCreateWithoutTournamentTeamInput[] | Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput | Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput[]
  createMany?: Prisma.TournamentPointCreateManyTournamentTeamInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUncheckedCreateNestedManyWithoutTournamentTeamInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput> | Prisma.TournamentPointCreateWithoutTournamentTeamInput[] | Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput | Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput[]
  createMany?: Prisma.TournamentPointCreateManyTournamentTeamInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUpdateManyWithoutTournamentTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput> | Prisma.TournamentPointCreateWithoutTournamentTeamInput[] | Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput | Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutTournamentTeamInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutTournamentTeamInput[]
  createMany?: Prisma.TournamentPointCreateManyTournamentTeamInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutTournamentTeamInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutTournamentTeamInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutTournamentTeamInput | Prisma.TournamentPointUpdateManyWithWhereWithoutTournamentTeamInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointUncheckedUpdateManyWithoutTournamentTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput> | Prisma.TournamentPointCreateWithoutTournamentTeamInput[] | Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput | Prisma.TournamentPointCreateOrConnectWithoutTournamentTeamInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutTournamentTeamInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutTournamentTeamInput[]
  createMany?: Prisma.TournamentPointCreateManyTournamentTeamInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutTournamentTeamInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutTournamentTeamInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutTournamentTeamInput | Prisma.TournamentPointUpdateManyWithWhereWithoutTournamentTeamInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput> | Prisma.TournamentPointCreateWithoutGameInput[] | Prisma.TournamentPointUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutGameInput | Prisma.TournamentPointCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.TournamentPointCreateManyGameInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput> | Prisma.TournamentPointCreateWithoutGameInput[] | Prisma.TournamentPointUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutGameInput | Prisma.TournamentPointCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.TournamentPointCreateManyGameInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput> | Prisma.TournamentPointCreateWithoutGameInput[] | Prisma.TournamentPointUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutGameInput | Prisma.TournamentPointCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutGameInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.TournamentPointCreateManyGameInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutGameInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutGameInput | Prisma.TournamentPointUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput> | Prisma.TournamentPointCreateWithoutGameInput[] | Prisma.TournamentPointUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutGameInput | Prisma.TournamentPointCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutGameInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.TournamentPointCreateManyGameInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutGameInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutGameInput | Prisma.TournamentPointUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointCreateNestedManyWithoutScorerInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput> | Prisma.TournamentPointCreateWithoutScorerInput[] | Prisma.TournamentPointUncheckedCreateWithoutScorerInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutScorerInput | Prisma.TournamentPointCreateOrConnectWithoutScorerInput[]
  createMany?: Prisma.TournamentPointCreateManyScorerInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUncheckedCreateNestedManyWithoutScorerInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput> | Prisma.TournamentPointCreateWithoutScorerInput[] | Prisma.TournamentPointUncheckedCreateWithoutScorerInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutScorerInput | Prisma.TournamentPointCreateOrConnectWithoutScorerInput[]
  createMany?: Prisma.TournamentPointCreateManyScorerInputEnvelope
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
}

export type TournamentPointUpdateManyWithoutScorerNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput> | Prisma.TournamentPointCreateWithoutScorerInput[] | Prisma.TournamentPointUncheckedCreateWithoutScorerInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutScorerInput | Prisma.TournamentPointCreateOrConnectWithoutScorerInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutScorerInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutScorerInput[]
  createMany?: Prisma.TournamentPointCreateManyScorerInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutScorerInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutScorerInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutScorerInput | Prisma.TournamentPointUpdateManyWithWhereWithoutScorerInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointUncheckedUpdateManyWithoutScorerNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput> | Prisma.TournamentPointCreateWithoutScorerInput[] | Prisma.TournamentPointUncheckedCreateWithoutScorerInput[]
  connectOrCreate?: Prisma.TournamentPointCreateOrConnectWithoutScorerInput | Prisma.TournamentPointCreateOrConnectWithoutScorerInput[]
  upsert?: Prisma.TournamentPointUpsertWithWhereUniqueWithoutScorerInput | Prisma.TournamentPointUpsertWithWhereUniqueWithoutScorerInput[]
  createMany?: Prisma.TournamentPointCreateManyScorerInputEnvelope
  set?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  disconnect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  delete?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  connect?: Prisma.TournamentPointWhereUniqueInput | Prisma.TournamentPointWhereUniqueInput[]
  update?: Prisma.TournamentPointUpdateWithWhereUniqueWithoutScorerInput | Prisma.TournamentPointUpdateWithWhereUniqueWithoutScorerInput[]
  updateMany?: Prisma.TournamentPointUpdateManyWithWhereWithoutScorerInput | Prisma.TournamentPointUpdateManyWithWhereWithoutScorerInput[]
  deleteMany?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
}

export type TournamentPointCreateWithoutTournamentTeamInput = {
  id?: string
  pointType?: string | null
  timestamp?: Date | string
  game: Prisma.TournamentGameCreateNestedOneWithoutTournamentPointsInput
  scorer?: Prisma.TournamentPlayerCreateNestedOneWithoutScoredPointsInput
}

export type TournamentPointUncheckedCreateWithoutTournamentTeamInput = {
  id?: string
  gameId: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
}

export type TournamentPointCreateOrConnectWithoutTournamentTeamInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput>
}

export type TournamentPointCreateManyTournamentTeamInputEnvelope = {
  data: Prisma.TournamentPointCreateManyTournamentTeamInput | Prisma.TournamentPointCreateManyTournamentTeamInput[]
  skipDuplicates?: boolean
}

export type TournamentPointUpsertWithWhereUniqueWithoutTournamentTeamInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentPointUpdateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedUpdateWithoutTournamentTeamInput>
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedCreateWithoutTournamentTeamInput>
}

export type TournamentPointUpdateWithWhereUniqueWithoutTournamentTeamInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateWithoutTournamentTeamInput, Prisma.TournamentPointUncheckedUpdateWithoutTournamentTeamInput>
}

export type TournamentPointUpdateManyWithWhereWithoutTournamentTeamInput = {
  where: Prisma.TournamentPointScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateManyMutationInput, Prisma.TournamentPointUncheckedUpdateManyWithoutTournamentTeamInput>
}

export type TournamentPointScalarWhereInput = {
  AND?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
  OR?: Prisma.TournamentPointScalarWhereInput[]
  NOT?: Prisma.TournamentPointScalarWhereInput | Prisma.TournamentPointScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentPoint"> | string
  gameId?: Prisma.StringFilter<"TournamentPoint"> | string
  scorerId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  pointType?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
  timestamp?: Prisma.DateTimeFilter<"TournamentPoint"> | Date | string
  tournamentTeamId?: Prisma.StringNullableFilter<"TournamentPoint"> | string | null
}

export type TournamentPointCreateWithoutGameInput = {
  id?: string
  pointType?: string | null
  timestamp?: Date | string
  scorer?: Prisma.TournamentPlayerCreateNestedOneWithoutScoredPointsInput
  tournamentTeam?: Prisma.TournamentTeamCreateNestedOneWithoutPointsLogInput
}

export type TournamentPointUncheckedCreateWithoutGameInput = {
  id?: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointCreateOrConnectWithoutGameInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput>
}

export type TournamentPointCreateManyGameInputEnvelope = {
  data: Prisma.TournamentPointCreateManyGameInput | Prisma.TournamentPointCreateManyGameInput[]
  skipDuplicates?: boolean
}

export type TournamentPointUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentPointUpdateWithoutGameInput, Prisma.TournamentPointUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutGameInput, Prisma.TournamentPointUncheckedCreateWithoutGameInput>
}

export type TournamentPointUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateWithoutGameInput, Prisma.TournamentPointUncheckedUpdateWithoutGameInput>
}

export type TournamentPointUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.TournamentPointScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateManyMutationInput, Prisma.TournamentPointUncheckedUpdateManyWithoutGameInput>
}

export type TournamentPointCreateWithoutScorerInput = {
  id?: string
  pointType?: string | null
  timestamp?: Date | string
  game: Prisma.TournamentGameCreateNestedOneWithoutTournamentPointsInput
  tournamentTeam?: Prisma.TournamentTeamCreateNestedOneWithoutPointsLogInput
}

export type TournamentPointUncheckedCreateWithoutScorerInput = {
  id?: string
  gameId: string
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointCreateOrConnectWithoutScorerInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput>
}

export type TournamentPointCreateManyScorerInputEnvelope = {
  data: Prisma.TournamentPointCreateManyScorerInput | Prisma.TournamentPointCreateManyScorerInput[]
  skipDuplicates?: boolean
}

export type TournamentPointUpsertWithWhereUniqueWithoutScorerInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentPointUpdateWithoutScorerInput, Prisma.TournamentPointUncheckedUpdateWithoutScorerInput>
  create: Prisma.XOR<Prisma.TournamentPointCreateWithoutScorerInput, Prisma.TournamentPointUncheckedCreateWithoutScorerInput>
}

export type TournamentPointUpdateWithWhereUniqueWithoutScorerInput = {
  where: Prisma.TournamentPointWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateWithoutScorerInput, Prisma.TournamentPointUncheckedUpdateWithoutScorerInput>
}

export type TournamentPointUpdateManyWithWhereWithoutScorerInput = {
  where: Prisma.TournamentPointScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentPointUpdateManyMutationInput, Prisma.TournamentPointUncheckedUpdateManyWithoutScorerInput>
}

export type TournamentPointCreateManyTournamentTeamInput = {
  id?: string
  gameId: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
}

export type TournamentPointUpdateWithoutTournamentTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  game?: Prisma.TournamentGameUpdateOneRequiredWithoutTournamentPointsNestedInput
  scorer?: Prisma.TournamentPlayerUpdateOneWithoutScoredPointsNestedInput
}

export type TournamentPointUncheckedUpdateWithoutTournamentTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPointUncheckedUpdateManyWithoutTournamentTeamInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentPointCreateManyGameInput = {
  id?: string
  scorerId?: string | null
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  scorer?: Prisma.TournamentPlayerUpdateOneWithoutScoredPointsNestedInput
  tournamentTeam?: Prisma.TournamentTeamUpdateOneWithoutPointsLogNestedInput
}

export type TournamentPointUncheckedUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TournamentPointUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scorerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TournamentPointCreateManyScorerInput = {
  id?: string
  gameId: string
  pointType?: string | null
  timestamp?: Date | string
  tournamentTeamId?: string | null
}

export type TournamentPointUpdateWithoutScorerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  game?: Prisma.TournamentGameUpdateOneRequiredWithoutTournamentPointsNestedInput
  tournamentTeam?: Prisma.TournamentTeamUpdateOneWithoutPointsLogNestedInput
}

export type TournamentPointUncheckedUpdateWithoutScorerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TournamentPointUncheckedUpdateManyWithoutScorerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  pointType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournamentTeamId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type TournamentPointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  scorerId?: boolean
  pointType?: boolean
  timestamp?: boolean
  tournamentTeamId?: boolean
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPoint"]>

export type TournamentPointSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  scorerId?: boolean
  pointType?: boolean
  timestamp?: boolean
  tournamentTeamId?: boolean
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPoint"]>

export type TournamentPointSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  scorerId?: boolean
  pointType?: boolean
  timestamp?: boolean
  tournamentTeamId?: boolean
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}, ExtArgs["result"]["tournamentPoint"]>

export type TournamentPointSelectScalar = {
  id?: boolean
  gameId?: boolean
  scorerId?: boolean
  pointType?: boolean
  timestamp?: boolean
  tournamentTeamId?: boolean
}

export type TournamentPointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gameId" | "scorerId" | "pointType" | "timestamp" | "tournamentTeamId", ExtArgs["result"]["tournamentPoint"]>
export type TournamentPointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}
export type TournamentPointIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}
export type TournamentPointIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.TournamentGameDefaultArgs<ExtArgs>
  scorer?: boolean | Prisma.TournamentPoint$scorerArgs<ExtArgs>
  tournamentTeam?: boolean | Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>
}

export type $TournamentPointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentPoint"
  objects: {
    game: Prisma.$TournamentGamePayload<ExtArgs>
    scorer: Prisma.$TournamentPlayerPayload<ExtArgs> | null
    tournamentTeam: Prisma.$TournamentTeamPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gameId: string
    scorerId: string | null
    pointType: string | null
    timestamp: Date
    tournamentTeamId: string | null
  }, ExtArgs["result"]["tournamentPoint"]>
  composites: {}
}

export type TournamentPointGetPayload<S extends boolean | null | undefined | TournamentPointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload, S>

export type TournamentPointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentPointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentPointCountAggregateInputType | true
  }

export interface TournamentPointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentPoint'], meta: { name: 'TournamentPoint' } }
  /**
   * Find zero or one TournamentPoint that matches the filter.
   * @param {TournamentPointFindUniqueArgs} args - Arguments to find a TournamentPoint
   * @example
   * // Get one TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentPointFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentPointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentPoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentPointFindUniqueOrThrowArgs} args - Arguments to find a TournamentPoint
   * @example
   * // Get one TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentPointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentPointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentPoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointFindFirstArgs} args - Arguments to find a TournamentPoint
   * @example
   * // Get one TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentPointFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentPointFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentPoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointFindFirstOrThrowArgs} args - Arguments to find a TournamentPoint
   * @example
   * // Get one TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentPointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentPointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentPoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentPoints
   * const tournamentPoints = await prisma.tournamentPoint.findMany()
   * 
   * // Get first 10 TournamentPoints
   * const tournamentPoints = await prisma.tournamentPoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentPointWithIdOnly = await prisma.tournamentPoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentPointFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentPointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentPoint.
   * @param {TournamentPointCreateArgs} args - Arguments to create a TournamentPoint.
   * @example
   * // Create one TournamentPoint
   * const TournamentPoint = await prisma.tournamentPoint.create({
   *   data: {
   *     // ... data to create a TournamentPoint
   *   }
   * })
   * 
   */
  create<T extends TournamentPointCreateArgs>(args: Prisma.SelectSubset<T, TournamentPointCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentPoints.
   * @param {TournamentPointCreateManyArgs} args - Arguments to create many TournamentPoints.
   * @example
   * // Create many TournamentPoints
   * const tournamentPoint = await prisma.tournamentPoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentPointCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentPointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentPoints and returns the data saved in the database.
   * @param {TournamentPointCreateManyAndReturnArgs} args - Arguments to create many TournamentPoints.
   * @example
   * // Create many TournamentPoints
   * const tournamentPoint = await prisma.tournamentPoint.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentPoints and only return the `id`
   * const tournamentPointWithIdOnly = await prisma.tournamentPoint.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentPointCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentPointCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentPoint.
   * @param {TournamentPointDeleteArgs} args - Arguments to delete one TournamentPoint.
   * @example
   * // Delete one TournamentPoint
   * const TournamentPoint = await prisma.tournamentPoint.delete({
   *   where: {
   *     // ... filter to delete one TournamentPoint
   *   }
   * })
   * 
   */
  delete<T extends TournamentPointDeleteArgs>(args: Prisma.SelectSubset<T, TournamentPointDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentPoint.
   * @param {TournamentPointUpdateArgs} args - Arguments to update one TournamentPoint.
   * @example
   * // Update one TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentPointUpdateArgs>(args: Prisma.SelectSubset<T, TournamentPointUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentPoints.
   * @param {TournamentPointDeleteManyArgs} args - Arguments to filter TournamentPoints to delete.
   * @example
   * // Delete a few TournamentPoints
   * const { count } = await prisma.tournamentPoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentPointDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentPointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentPoints
   * const tournamentPoint = await prisma.tournamentPoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentPointUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentPointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentPoints and returns the data updated in the database.
   * @param {TournamentPointUpdateManyAndReturnArgs} args - Arguments to update many TournamentPoints.
   * @example
   * // Update many TournamentPoints
   * const tournamentPoint = await prisma.tournamentPoint.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentPoints and only return the `id`
   * const tournamentPointWithIdOnly = await prisma.tournamentPoint.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentPointUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentPointUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentPoint.
   * @param {TournamentPointUpsertArgs} args - Arguments to update or create a TournamentPoint.
   * @example
   * // Update or create a TournamentPoint
   * const tournamentPoint = await prisma.tournamentPoint.upsert({
   *   create: {
   *     // ... data to create a TournamentPoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentPoint we want to update
   *   }
   * })
   */
  upsert<T extends TournamentPointUpsertArgs>(args: Prisma.SelectSubset<T, TournamentPointUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentPointClient<runtime.Types.Result.GetResult<Prisma.$TournamentPointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointCountArgs} args - Arguments to filter TournamentPoints to count.
   * @example
   * // Count the number of TournamentPoints
   * const count = await prisma.tournamentPoint.count({
   *   where: {
   *     // ... the filter for the TournamentPoints we want to count
   *   }
   * })
  **/
  count<T extends TournamentPointCountArgs>(
    args?: Prisma.Subset<T, TournamentPointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentPointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentPointAggregateArgs>(args: Prisma.Subset<T, TournamentPointAggregateArgs>): Prisma.PrismaPromise<GetTournamentPointAggregateType<T>>

  /**
   * Group by TournamentPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentPointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentPointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentPointGroupByArgs['orderBy'] }
      : { orderBy?: TournamentPointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentPointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentPointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentPoint model
 */
readonly fields: TournamentPointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentPoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentPointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.TournamentGameDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentGameDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentGameClient<runtime.Types.Result.GetResult<Prisma.$TournamentGamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  scorer<T extends Prisma.TournamentPoint$scorerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentPoint$scorerArgs<ExtArgs>>): Prisma.Prisma__TournamentPlayerClient<runtime.Types.Result.GetResult<Prisma.$TournamentPlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  tournamentTeam<T extends Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentPoint$tournamentTeamArgs<ExtArgs>>): Prisma.Prisma__TournamentTeamClient<runtime.Types.Result.GetResult<Prisma.$TournamentTeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentPoint model
 */
export interface TournamentPointFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentPoint", 'String'>
  readonly gameId: Prisma.FieldRef<"TournamentPoint", 'String'>
  readonly scorerId: Prisma.FieldRef<"TournamentPoint", 'String'>
  readonly pointType: Prisma.FieldRef<"TournamentPoint", 'String'>
  readonly timestamp: Prisma.FieldRef<"TournamentPoint", 'DateTime'>
  readonly tournamentTeamId: Prisma.FieldRef<"TournamentPoint", 'String'>
}
    

// Custom InputTypes
/**
 * TournamentPoint findUnique
 */
export type TournamentPointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPoint to fetch.
   */
  where: Prisma.TournamentPointWhereUniqueInput
}

/**
 * TournamentPoint findUniqueOrThrow
 */
export type TournamentPointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPoint to fetch.
   */
  where: Prisma.TournamentPointWhereUniqueInput
}

/**
 * TournamentPoint findFirst
 */
export type TournamentPointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPoint to fetch.
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPoints to fetch.
   */
  orderBy?: Prisma.TournamentPointOrderByWithRelationInput | Prisma.TournamentPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentPoints.
   */
  cursor?: Prisma.TournamentPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentPoints.
   */
  distinct?: Prisma.TournamentPointScalarFieldEnum | Prisma.TournamentPointScalarFieldEnum[]
}

/**
 * TournamentPoint findFirstOrThrow
 */
export type TournamentPointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPoint to fetch.
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPoints to fetch.
   */
  orderBy?: Prisma.TournamentPointOrderByWithRelationInput | Prisma.TournamentPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentPoints.
   */
  cursor?: Prisma.TournamentPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentPoints.
   */
  distinct?: Prisma.TournamentPointScalarFieldEnum | Prisma.TournamentPointScalarFieldEnum[]
}

/**
 * TournamentPoint findMany
 */
export type TournamentPointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter, which TournamentPoints to fetch.
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentPoints to fetch.
   */
  orderBy?: Prisma.TournamentPointOrderByWithRelationInput | Prisma.TournamentPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentPoints.
   */
  cursor?: Prisma.TournamentPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentPoints.
   */
  skip?: number
  distinct?: Prisma.TournamentPointScalarFieldEnum | Prisma.TournamentPointScalarFieldEnum[]
}

/**
 * TournamentPoint create
 */
export type TournamentPointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentPoint.
   */
  data: Prisma.XOR<Prisma.TournamentPointCreateInput, Prisma.TournamentPointUncheckedCreateInput>
}

/**
 * TournamentPoint createMany
 */
export type TournamentPointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentPoints.
   */
  data: Prisma.TournamentPointCreateManyInput | Prisma.TournamentPointCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TournamentPoint createManyAndReturn
 */
export type TournamentPointCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentPoints.
   */
  data: Prisma.TournamentPointCreateManyInput | Prisma.TournamentPointCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentPoint update
 */
export type TournamentPointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentPoint.
   */
  data: Prisma.XOR<Prisma.TournamentPointUpdateInput, Prisma.TournamentPointUncheckedUpdateInput>
  /**
   * Choose, which TournamentPoint to update.
   */
  where: Prisma.TournamentPointWhereUniqueInput
}

/**
 * TournamentPoint updateMany
 */
export type TournamentPointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentPoints.
   */
  data: Prisma.XOR<Prisma.TournamentPointUpdateManyMutationInput, Prisma.TournamentPointUncheckedUpdateManyInput>
  /**
   * Filter which TournamentPoints to update
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * Limit how many TournamentPoints to update.
   */
  limit?: number
}

/**
 * TournamentPoint updateManyAndReturn
 */
export type TournamentPointUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * The data used to update TournamentPoints.
   */
  data: Prisma.XOR<Prisma.TournamentPointUpdateManyMutationInput, Prisma.TournamentPointUncheckedUpdateManyInput>
  /**
   * Filter which TournamentPoints to update
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * Limit how many TournamentPoints to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentPoint upsert
 */
export type TournamentPointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentPoint to update in case it exists.
   */
  where: Prisma.TournamentPointWhereUniqueInput
  /**
   * In case the TournamentPoint found by the `where` argument doesn't exist, create a new TournamentPoint with this data.
   */
  create: Prisma.XOR<Prisma.TournamentPointCreateInput, Prisma.TournamentPointUncheckedCreateInput>
  /**
   * In case the TournamentPoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentPointUpdateInput, Prisma.TournamentPointUncheckedUpdateInput>
}

/**
 * TournamentPoint delete
 */
export type TournamentPointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
  /**
   * Filter which TournamentPoint to delete.
   */
  where: Prisma.TournamentPointWhereUniqueInput
}

/**
 * TournamentPoint deleteMany
 */
export type TournamentPointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentPoints to delete
   */
  where?: Prisma.TournamentPointWhereInput
  /**
   * Limit how many TournamentPoints to delete.
   */
  limit?: number
}

/**
 * TournamentPoint.scorer
 */
export type TournamentPoint$scorerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPlayer
   */
  select?: Prisma.TournamentPlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPlayer
   */
  omit?: Prisma.TournamentPlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPlayerInclude<ExtArgs> | null
  where?: Prisma.TournamentPlayerWhereInput
}

/**
 * TournamentPoint.tournamentTeam
 */
export type TournamentPoint$tournamentTeamArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentTeam
   */
  select?: Prisma.TournamentTeamSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentTeam
   */
  omit?: Prisma.TournamentTeamOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentTeamInclude<ExtArgs> | null
  where?: Prisma.TournamentTeamWhereInput
}

/**
 * TournamentPoint without action
 */
export type TournamentPointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentPoint
   */
  select?: Prisma.TournamentPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentPoint
   */
  omit?: Prisma.TournamentPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentPointInclude<ExtArgs> | null
}
