
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TournamentEnrollment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TournamentEnrollment
 * 
 */
export type TournamentEnrollmentModel = runtime.Types.Result.DefaultSelection<Prisma.$TournamentEnrollmentPayload>

export type AggregateTournamentEnrollment = {
  _count: TournamentEnrollmentCountAggregateOutputType | null
  _min: TournamentEnrollmentMinAggregateOutputType | null
  _max: TournamentEnrollmentMaxAggregateOutputType | null
}

export type TournamentEnrollmentMinAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  userId: string | null
  name: string | null
  email: string | null
  mobile: string | null
  paymentMode: $Enums.PaymentMode | null
  paymentScreenshotUrl: string | null
  transactionId: string | null
  status: $Enums.EnrollmentStatus | null
  adminNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentEnrollmentMaxAggregateOutputType = {
  id: string | null
  tournamentId: string | null
  userId: string | null
  name: string | null
  email: string | null
  mobile: string | null
  paymentMode: $Enums.PaymentMode | null
  paymentScreenshotUrl: string | null
  transactionId: string | null
  status: $Enums.EnrollmentStatus | null
  adminNotes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type TournamentEnrollmentCountAggregateOutputType = {
  id: number
  tournamentId: number
  userId: number
  name: number
  email: number
  mobile: number
  paymentMode: number
  paymentScreenshotUrl: number
  transactionId: number
  status: number
  adminNotes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type TournamentEnrollmentMinAggregateInputType = {
  id?: true
  tournamentId?: true
  userId?: true
  name?: true
  email?: true
  mobile?: true
  paymentMode?: true
  paymentScreenshotUrl?: true
  transactionId?: true
  status?: true
  adminNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentEnrollmentMaxAggregateInputType = {
  id?: true
  tournamentId?: true
  userId?: true
  name?: true
  email?: true
  mobile?: true
  paymentMode?: true
  paymentScreenshotUrl?: true
  transactionId?: true
  status?: true
  adminNotes?: true
  createdAt?: true
  updatedAt?: true
}

export type TournamentEnrollmentCountAggregateInputType = {
  id?: true
  tournamentId?: true
  userId?: true
  name?: true
  email?: true
  mobile?: true
  paymentMode?: true
  paymentScreenshotUrl?: true
  transactionId?: true
  status?: true
  adminNotes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type TournamentEnrollmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentEnrollment to aggregate.
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentEnrollments to fetch.
   */
  orderBy?: Prisma.TournamentEnrollmentOrderByWithRelationInput | Prisma.TournamentEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TournamentEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TournamentEnrollments
  **/
  _count?: true | TournamentEnrollmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TournamentEnrollmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TournamentEnrollmentMaxAggregateInputType
}

export type GetTournamentEnrollmentAggregateType<T extends TournamentEnrollmentAggregateArgs> = {
      [P in keyof T & keyof AggregateTournamentEnrollment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTournamentEnrollment[P]>
    : Prisma.GetScalarType<T[P], AggregateTournamentEnrollment[P]>
}




export type TournamentEnrollmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TournamentEnrollmentWhereInput
  orderBy?: Prisma.TournamentEnrollmentOrderByWithAggregationInput | Prisma.TournamentEnrollmentOrderByWithAggregationInput[]
  by: Prisma.TournamentEnrollmentScalarFieldEnum[] | Prisma.TournamentEnrollmentScalarFieldEnum
  having?: Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TournamentEnrollmentCountAggregateInputType | true
  _min?: TournamentEnrollmentMinAggregateInputType
  _max?: TournamentEnrollmentMaxAggregateInputType
}

export type TournamentEnrollmentGroupByOutputType = {
  id: string
  tournamentId: string
  userId: string | null
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl: string | null
  transactionId: string | null
  status: $Enums.EnrollmentStatus
  adminNotes: string | null
  createdAt: Date
  updatedAt: Date
  _count: TournamentEnrollmentCountAggregateOutputType | null
  _min: TournamentEnrollmentMinAggregateOutputType | null
  _max: TournamentEnrollmentMaxAggregateOutputType | null
}

type GetTournamentEnrollmentGroupByPayload<T extends TournamentEnrollmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TournamentEnrollmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TournamentEnrollmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TournamentEnrollmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TournamentEnrollmentGroupByOutputType[P]>
      }
    >
  >



export type TournamentEnrollmentWhereInput = {
  AND?: Prisma.TournamentEnrollmentWhereInput | Prisma.TournamentEnrollmentWhereInput[]
  OR?: Prisma.TournamentEnrollmentWhereInput[]
  NOT?: Prisma.TournamentEnrollmentWhereInput | Prisma.TournamentEnrollmentWhereInput[]
  id?: Prisma.StringFilter<"TournamentEnrollment"> | string
  tournamentId?: Prisma.StringFilter<"TournamentEnrollment"> | string
  userId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  name?: Prisma.StringFilter<"TournamentEnrollment"> | string
  email?: Prisma.StringFilter<"TournamentEnrollment"> | string
  mobile?: Prisma.StringFilter<"TournamentEnrollment"> | string
  paymentMode?: Prisma.EnumPaymentModeFilter<"TournamentEnrollment"> | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  transactionId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  status?: Prisma.EnumEnrollmentStatusFilter<"TournamentEnrollment"> | $Enums.EnrollmentStatus
  adminNotes?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type TournamentEnrollmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  paymentMode?: Prisma.SortOrder
  paymentScreenshotUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  tournament?: Prisma.TournamentOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type TournamentEnrollmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TournamentEnrollmentWhereInput | Prisma.TournamentEnrollmentWhereInput[]
  OR?: Prisma.TournamentEnrollmentWhereInput[]
  NOT?: Prisma.TournamentEnrollmentWhereInput | Prisma.TournamentEnrollmentWhereInput[]
  tournamentId?: Prisma.StringFilter<"TournamentEnrollment"> | string
  userId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  name?: Prisma.StringFilter<"TournamentEnrollment"> | string
  email?: Prisma.StringFilter<"TournamentEnrollment"> | string
  mobile?: Prisma.StringFilter<"TournamentEnrollment"> | string
  paymentMode?: Prisma.EnumPaymentModeFilter<"TournamentEnrollment"> | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  transactionId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  status?: Prisma.EnumEnrollmentStatusFilter<"TournamentEnrollment"> | $Enums.EnrollmentStatus
  adminNotes?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
  tournament?: Prisma.XOR<Prisma.TournamentScalarRelationFilter, Prisma.TournamentWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type TournamentEnrollmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  paymentMode?: Prisma.SortOrder
  paymentScreenshotUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  transactionId?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.TournamentEnrollmentCountOrderByAggregateInput
  _max?: Prisma.TournamentEnrollmentMaxOrderByAggregateInput
  _min?: Prisma.TournamentEnrollmentMinOrderByAggregateInput
}

export type TournamentEnrollmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput | Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput | Prisma.TournamentEnrollmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TournamentEnrollment"> | string
  tournamentId?: Prisma.StringWithAggregatesFilter<"TournamentEnrollment"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"TournamentEnrollment"> | string | null
  name?: Prisma.StringWithAggregatesFilter<"TournamentEnrollment"> | string
  email?: Prisma.StringWithAggregatesFilter<"TournamentEnrollment"> | string
  mobile?: Prisma.StringWithAggregatesFilter<"TournamentEnrollment"> | string
  paymentMode?: Prisma.EnumPaymentModeWithAggregatesFilter<"TournamentEnrollment"> | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.StringNullableWithAggregatesFilter<"TournamentEnrollment"> | string | null
  transactionId?: Prisma.StringNullableWithAggregatesFilter<"TournamentEnrollment"> | string | null
  status?: Prisma.EnumEnrollmentStatusWithAggregatesFilter<"TournamentEnrollment"> | $Enums.EnrollmentStatus
  adminNotes?: Prisma.StringNullableWithAggregatesFilter<"TournamentEnrollment"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentEnrollment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"TournamentEnrollment"> | Date | string
}

export type TournamentEnrollmentCreateInput = {
  id?: string
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tournament: Prisma.TournamentCreateNestedOneWithoutEnrollmentsInput
  user?: Prisma.UserCreateNestedOneWithoutTournamentEnrollmentsInput
}

export type TournamentEnrollmentUncheckedCreateInput = {
  id?: string
  tournamentId: string
  userId?: string | null
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournament?: Prisma.TournamentUpdateOneRequiredWithoutEnrollmentsNestedInput
  user?: Prisma.UserUpdateOneWithoutTournamentEnrollmentsNestedInput
}

export type TournamentEnrollmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentCreateManyInput = {
  id?: string
  tournamentId: string
  userId?: string | null
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentListRelationFilter = {
  every?: Prisma.TournamentEnrollmentWhereInput
  some?: Prisma.TournamentEnrollmentWhereInput
  none?: Prisma.TournamentEnrollmentWhereInput
}

export type TournamentEnrollmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TournamentEnrollmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  paymentMode?: Prisma.SortOrder
  paymentScreenshotUrl?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentEnrollmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  paymentMode?: Prisma.SortOrder
  paymentScreenshotUrl?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentEnrollmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tournamentId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  mobile?: Prisma.SortOrder
  paymentMode?: Prisma.SortOrder
  paymentScreenshotUrl?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  adminNotes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type TournamentEnrollmentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput> | Prisma.TournamentEnrollmentCreateWithoutUserInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyUserInputEnvelope
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
}

export type TournamentEnrollmentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput> | Prisma.TournamentEnrollmentCreateWithoutUserInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyUserInputEnvelope
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
}

export type TournamentEnrollmentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput> | Prisma.TournamentEnrollmentCreateWithoutUserInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyUserInputEnvelope
  set?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  delete?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  update?: Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutUserInput | Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
}

export type TournamentEnrollmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput> | Prisma.TournamentEnrollmentCreateWithoutUserInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutUserInput | Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyUserInputEnvelope
  set?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  delete?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  update?: Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutUserInput | Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutUserInput | Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
}

export type TournamentEnrollmentCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput> | Prisma.TournamentEnrollmentCreateWithoutTournamentInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
}

export type TournamentEnrollmentUncheckedCreateNestedManyWithoutTournamentInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput> | Prisma.TournamentEnrollmentCreateWithoutTournamentInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyTournamentInputEnvelope
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
}

export type TournamentEnrollmentUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput> | Prisma.TournamentEnrollmentCreateWithoutTournamentInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  delete?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  update?: Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
}

export type TournamentEnrollmentUncheckedUpdateManyWithoutTournamentNestedInput = {
  create?: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput> | Prisma.TournamentEnrollmentCreateWithoutTournamentInput[] | Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput[]
  connectOrCreate?: Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput | Prisma.TournamentEnrollmentCreateOrConnectWithoutTournamentInput[]
  upsert?: Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutTournamentInput | Prisma.TournamentEnrollmentUpsertWithWhereUniqueWithoutTournamentInput[]
  createMany?: Prisma.TournamentEnrollmentCreateManyTournamentInputEnvelope
  set?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  disconnect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  delete?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  connect?: Prisma.TournamentEnrollmentWhereUniqueInput | Prisma.TournamentEnrollmentWhereUniqueInput[]
  update?: Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutTournamentInput | Prisma.TournamentEnrollmentUpdateWithWhereUniqueWithoutTournamentInput[]
  updateMany?: Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutTournamentInput | Prisma.TournamentEnrollmentUpdateManyWithWhereWithoutTournamentInput[]
  deleteMany?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
}

export type EnumPaymentModeFieldUpdateOperationsInput = {
  set?: $Enums.PaymentMode
}

export type EnumEnrollmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.EnrollmentStatus
}

export type TournamentEnrollmentCreateWithoutUserInput = {
  id?: string
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  tournament: Prisma.TournamentCreateNestedOneWithoutEnrollmentsInput
}

export type TournamentEnrollmentUncheckedCreateWithoutUserInput = {
  id?: string
  tournamentId: string
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentCreateOrConnectWithoutUserInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput>
}

export type TournamentEnrollmentCreateManyUserInputEnvelope = {
  data: Prisma.TournamentEnrollmentCreateManyUserInput | Prisma.TournamentEnrollmentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TournamentEnrollmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentEnrollmentUpdateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutUserInput>
}

export type TournamentEnrollmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateWithoutUserInput, Prisma.TournamentEnrollmentUncheckedUpdateWithoutUserInput>
}

export type TournamentEnrollmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TournamentEnrollmentScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateManyMutationInput, Prisma.TournamentEnrollmentUncheckedUpdateManyWithoutUserInput>
}

export type TournamentEnrollmentScalarWhereInput = {
  AND?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
  OR?: Prisma.TournamentEnrollmentScalarWhereInput[]
  NOT?: Prisma.TournamentEnrollmentScalarWhereInput | Prisma.TournamentEnrollmentScalarWhereInput[]
  id?: Prisma.StringFilter<"TournamentEnrollment"> | string
  tournamentId?: Prisma.StringFilter<"TournamentEnrollment"> | string
  userId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  name?: Prisma.StringFilter<"TournamentEnrollment"> | string
  email?: Prisma.StringFilter<"TournamentEnrollment"> | string
  mobile?: Prisma.StringFilter<"TournamentEnrollment"> | string
  paymentMode?: Prisma.EnumPaymentModeFilter<"TournamentEnrollment"> | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  transactionId?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  status?: Prisma.EnumEnrollmentStatusFilter<"TournamentEnrollment"> | $Enums.EnrollmentStatus
  adminNotes?: Prisma.StringNullableFilter<"TournamentEnrollment"> | string | null
  createdAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"TournamentEnrollment"> | Date | string
}

export type TournamentEnrollmentCreateWithoutTournamentInput = {
  id?: string
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutTournamentEnrollmentsInput
}

export type TournamentEnrollmentUncheckedCreateWithoutTournamentInput = {
  id?: string
  userId?: string | null
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentCreateOrConnectWithoutTournamentInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  create: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput>
}

export type TournamentEnrollmentCreateManyTournamentInputEnvelope = {
  data: Prisma.TournamentEnrollmentCreateManyTournamentInput | Prisma.TournamentEnrollmentCreateManyTournamentInput[]
  skipDuplicates?: boolean
}

export type TournamentEnrollmentUpsertWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  update: Prisma.XOR<Prisma.TournamentEnrollmentUpdateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedUpdateWithoutTournamentInput>
  create: Prisma.XOR<Prisma.TournamentEnrollmentCreateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedCreateWithoutTournamentInput>
}

export type TournamentEnrollmentUpdateWithWhereUniqueWithoutTournamentInput = {
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateWithoutTournamentInput, Prisma.TournamentEnrollmentUncheckedUpdateWithoutTournamentInput>
}

export type TournamentEnrollmentUpdateManyWithWhereWithoutTournamentInput = {
  where: Prisma.TournamentEnrollmentScalarWhereInput
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateManyMutationInput, Prisma.TournamentEnrollmentUncheckedUpdateManyWithoutTournamentInput>
}

export type TournamentEnrollmentCreateManyUserInput = {
  id?: string
  tournamentId: string
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  tournament?: Prisma.TournamentUpdateOneRequiredWithoutEnrollmentsNestedInput
}

export type TournamentEnrollmentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tournamentId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentCreateManyTournamentInput = {
  id?: string
  userId?: string | null
  name: string
  email: string
  mobile: string
  paymentMode: $Enums.PaymentMode
  paymentScreenshotUrl?: string | null
  transactionId?: string | null
  status?: $Enums.EnrollmentStatus
  adminNotes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type TournamentEnrollmentUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutTournamentEnrollmentsNestedInput
}

export type TournamentEnrollmentUncheckedUpdateWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TournamentEnrollmentUncheckedUpdateManyWithoutTournamentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  mobile?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMode?: Prisma.EnumPaymentModeFieldUpdateOperationsInput | $Enums.PaymentMode
  paymentScreenshotUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  transactionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumEnrollmentStatusFieldUpdateOperationsInput | $Enums.EnrollmentStatus
  adminNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TournamentEnrollmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  mobile?: boolean
  paymentMode?: boolean
  paymentScreenshotUrl?: boolean
  transactionId?: boolean
  status?: boolean
  adminNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}, ExtArgs["result"]["tournamentEnrollment"]>

export type TournamentEnrollmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  mobile?: boolean
  paymentMode?: boolean
  paymentScreenshotUrl?: boolean
  transactionId?: boolean
  status?: boolean
  adminNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}, ExtArgs["result"]["tournamentEnrollment"]>

export type TournamentEnrollmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tournamentId?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  mobile?: boolean
  paymentMode?: boolean
  paymentScreenshotUrl?: boolean
  transactionId?: boolean
  status?: boolean
  adminNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}, ExtArgs["result"]["tournamentEnrollment"]>

export type TournamentEnrollmentSelectScalar = {
  id?: boolean
  tournamentId?: boolean
  userId?: boolean
  name?: boolean
  email?: boolean
  mobile?: boolean
  paymentMode?: boolean
  paymentScreenshotUrl?: boolean
  transactionId?: boolean
  status?: boolean
  adminNotes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type TournamentEnrollmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tournamentId" | "userId" | "name" | "email" | "mobile" | "paymentMode" | "paymentScreenshotUrl" | "transactionId" | "status" | "adminNotes" | "createdAt" | "updatedAt", ExtArgs["result"]["tournamentEnrollment"]>
export type TournamentEnrollmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}
export type TournamentEnrollmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}
export type TournamentEnrollmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tournament?: boolean | Prisma.TournamentDefaultArgs<ExtArgs>
  user?: boolean | Prisma.TournamentEnrollment$userArgs<ExtArgs>
}

export type $TournamentEnrollmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TournamentEnrollment"
  objects: {
    tournament: Prisma.$TournamentPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tournamentId: string
    userId: string | null
    name: string
    email: string
    mobile: string
    paymentMode: $Enums.PaymentMode
    paymentScreenshotUrl: string | null
    transactionId: string | null
    status: $Enums.EnrollmentStatus
    adminNotes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["tournamentEnrollment"]>
  composites: {}
}

export type TournamentEnrollmentGetPayload<S extends boolean | null | undefined | TournamentEnrollmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload, S>

export type TournamentEnrollmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TournamentEnrollmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TournamentEnrollmentCountAggregateInputType | true
  }

export interface TournamentEnrollmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TournamentEnrollment'], meta: { name: 'TournamentEnrollment' } }
  /**
   * Find zero or one TournamentEnrollment that matches the filter.
   * @param {TournamentEnrollmentFindUniqueArgs} args - Arguments to find a TournamentEnrollment
   * @example
   * // Get one TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TournamentEnrollmentFindUniqueArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TournamentEnrollment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TournamentEnrollmentFindUniqueOrThrowArgs} args - Arguments to find a TournamentEnrollment
   * @example
   * // Get one TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TournamentEnrollmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentEnrollment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentFindFirstArgs} args - Arguments to find a TournamentEnrollment
   * @example
   * // Get one TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TournamentEnrollmentFindFirstArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TournamentEnrollment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentFindFirstOrThrowArgs} args - Arguments to find a TournamentEnrollment
   * @example
   * // Get one TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TournamentEnrollmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TournamentEnrollments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TournamentEnrollments
   * const tournamentEnrollments = await prisma.tournamentEnrollment.findMany()
   * 
   * // Get first 10 TournamentEnrollments
   * const tournamentEnrollments = await prisma.tournamentEnrollment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const tournamentEnrollmentWithIdOnly = await prisma.tournamentEnrollment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TournamentEnrollmentFindManyArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TournamentEnrollment.
   * @param {TournamentEnrollmentCreateArgs} args - Arguments to create a TournamentEnrollment.
   * @example
   * // Create one TournamentEnrollment
   * const TournamentEnrollment = await prisma.tournamentEnrollment.create({
   *   data: {
   *     // ... data to create a TournamentEnrollment
   *   }
   * })
   * 
   */
  create<T extends TournamentEnrollmentCreateArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentCreateArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TournamentEnrollments.
   * @param {TournamentEnrollmentCreateManyArgs} args - Arguments to create many TournamentEnrollments.
   * @example
   * // Create many TournamentEnrollments
   * const tournamentEnrollment = await prisma.tournamentEnrollment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TournamentEnrollmentCreateManyArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TournamentEnrollments and returns the data saved in the database.
   * @param {TournamentEnrollmentCreateManyAndReturnArgs} args - Arguments to create many TournamentEnrollments.
   * @example
   * // Create many TournamentEnrollments
   * const tournamentEnrollment = await prisma.tournamentEnrollment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TournamentEnrollments and only return the `id`
   * const tournamentEnrollmentWithIdOnly = await prisma.tournamentEnrollment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TournamentEnrollmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TournamentEnrollment.
   * @param {TournamentEnrollmentDeleteArgs} args - Arguments to delete one TournamentEnrollment.
   * @example
   * // Delete one TournamentEnrollment
   * const TournamentEnrollment = await prisma.tournamentEnrollment.delete({
   *   where: {
   *     // ... filter to delete one TournamentEnrollment
   *   }
   * })
   * 
   */
  delete<T extends TournamentEnrollmentDeleteArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentDeleteArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TournamentEnrollment.
   * @param {TournamentEnrollmentUpdateArgs} args - Arguments to update one TournamentEnrollment.
   * @example
   * // Update one TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TournamentEnrollmentUpdateArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentUpdateArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TournamentEnrollments.
   * @param {TournamentEnrollmentDeleteManyArgs} args - Arguments to filter TournamentEnrollments to delete.
   * @example
   * // Delete a few TournamentEnrollments
   * const { count } = await prisma.tournamentEnrollment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TournamentEnrollmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TournamentEnrollmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentEnrollments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TournamentEnrollments
   * const tournamentEnrollment = await prisma.tournamentEnrollment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TournamentEnrollmentUpdateManyArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TournamentEnrollments and returns the data updated in the database.
   * @param {TournamentEnrollmentUpdateManyAndReturnArgs} args - Arguments to update many TournamentEnrollments.
   * @example
   * // Update many TournamentEnrollments
   * const tournamentEnrollment = await prisma.tournamentEnrollment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TournamentEnrollments and only return the `id`
   * const tournamentEnrollmentWithIdOnly = await prisma.tournamentEnrollment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TournamentEnrollmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TournamentEnrollment.
   * @param {TournamentEnrollmentUpsertArgs} args - Arguments to update or create a TournamentEnrollment.
   * @example
   * // Update or create a TournamentEnrollment
   * const tournamentEnrollment = await prisma.tournamentEnrollment.upsert({
   *   create: {
   *     // ... data to create a TournamentEnrollment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TournamentEnrollment we want to update
   *   }
   * })
   */
  upsert<T extends TournamentEnrollmentUpsertArgs>(args: Prisma.SelectSubset<T, TournamentEnrollmentUpsertArgs<ExtArgs>>): Prisma.Prisma__TournamentEnrollmentClient<runtime.Types.Result.GetResult<Prisma.$TournamentEnrollmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TournamentEnrollments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentCountArgs} args - Arguments to filter TournamentEnrollments to count.
   * @example
   * // Count the number of TournamentEnrollments
   * const count = await prisma.tournamentEnrollment.count({
   *   where: {
   *     // ... the filter for the TournamentEnrollments we want to count
   *   }
   * })
  **/
  count<T extends TournamentEnrollmentCountArgs>(
    args?: Prisma.Subset<T, TournamentEnrollmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TournamentEnrollmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TournamentEnrollment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TournamentEnrollmentAggregateArgs>(args: Prisma.Subset<T, TournamentEnrollmentAggregateArgs>): Prisma.PrismaPromise<GetTournamentEnrollmentAggregateType<T>>

  /**
   * Group by TournamentEnrollment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TournamentEnrollmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TournamentEnrollmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TournamentEnrollmentGroupByArgs['orderBy'] }
      : { orderBy?: TournamentEnrollmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TournamentEnrollmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTournamentEnrollmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TournamentEnrollment model
 */
readonly fields: TournamentEnrollmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TournamentEnrollment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TournamentEnrollmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tournament<T extends Prisma.TournamentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentDefaultArgs<ExtArgs>>): Prisma.Prisma__TournamentClient<runtime.Types.Result.GetResult<Prisma.$TournamentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.TournamentEnrollment$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TournamentEnrollment$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TournamentEnrollment model
 */
export interface TournamentEnrollmentFieldRefs {
  readonly id: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly tournamentId: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly userId: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly name: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly email: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly mobile: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly paymentMode: Prisma.FieldRef<"TournamentEnrollment", 'PaymentMode'>
  readonly paymentScreenshotUrl: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly transactionId: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly status: Prisma.FieldRef<"TournamentEnrollment", 'EnrollmentStatus'>
  readonly adminNotes: Prisma.FieldRef<"TournamentEnrollment", 'String'>
  readonly createdAt: Prisma.FieldRef<"TournamentEnrollment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"TournamentEnrollment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TournamentEnrollment findUnique
 */
export type TournamentEnrollmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which TournamentEnrollment to fetch.
   */
  where: Prisma.TournamentEnrollmentWhereUniqueInput
}

/**
 * TournamentEnrollment findUniqueOrThrow
 */
export type TournamentEnrollmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which TournamentEnrollment to fetch.
   */
  where: Prisma.TournamentEnrollmentWhereUniqueInput
}

/**
 * TournamentEnrollment findFirst
 */
export type TournamentEnrollmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which TournamentEnrollment to fetch.
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentEnrollments to fetch.
   */
  orderBy?: Prisma.TournamentEnrollmentOrderByWithRelationInput | Prisma.TournamentEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentEnrollments.
   */
  cursor?: Prisma.TournamentEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentEnrollments.
   */
  distinct?: Prisma.TournamentEnrollmentScalarFieldEnum | Prisma.TournamentEnrollmentScalarFieldEnum[]
}

/**
 * TournamentEnrollment findFirstOrThrow
 */
export type TournamentEnrollmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which TournamentEnrollment to fetch.
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentEnrollments to fetch.
   */
  orderBy?: Prisma.TournamentEnrollmentOrderByWithRelationInput | Prisma.TournamentEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TournamentEnrollments.
   */
  cursor?: Prisma.TournamentEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentEnrollments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TournamentEnrollments.
   */
  distinct?: Prisma.TournamentEnrollmentScalarFieldEnum | Prisma.TournamentEnrollmentScalarFieldEnum[]
}

/**
 * TournamentEnrollment findMany
 */
export type TournamentEnrollmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter, which TournamentEnrollments to fetch.
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TournamentEnrollments to fetch.
   */
  orderBy?: Prisma.TournamentEnrollmentOrderByWithRelationInput | Prisma.TournamentEnrollmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TournamentEnrollments.
   */
  cursor?: Prisma.TournamentEnrollmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TournamentEnrollments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TournamentEnrollments.
   */
  skip?: number
  distinct?: Prisma.TournamentEnrollmentScalarFieldEnum | Prisma.TournamentEnrollmentScalarFieldEnum[]
}

/**
 * TournamentEnrollment create
 */
export type TournamentEnrollmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * The data needed to create a TournamentEnrollment.
   */
  data: Prisma.XOR<Prisma.TournamentEnrollmentCreateInput, Prisma.TournamentEnrollmentUncheckedCreateInput>
}

/**
 * TournamentEnrollment createMany
 */
export type TournamentEnrollmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TournamentEnrollments.
   */
  data: Prisma.TournamentEnrollmentCreateManyInput | Prisma.TournamentEnrollmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TournamentEnrollment createManyAndReturn
 */
export type TournamentEnrollmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * The data used to create many TournamentEnrollments.
   */
  data: Prisma.TournamentEnrollmentCreateManyInput | Prisma.TournamentEnrollmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentEnrollment update
 */
export type TournamentEnrollmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * The data needed to update a TournamentEnrollment.
   */
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateInput, Prisma.TournamentEnrollmentUncheckedUpdateInput>
  /**
   * Choose, which TournamentEnrollment to update.
   */
  where: Prisma.TournamentEnrollmentWhereUniqueInput
}

/**
 * TournamentEnrollment updateMany
 */
export type TournamentEnrollmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TournamentEnrollments.
   */
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateManyMutationInput, Prisma.TournamentEnrollmentUncheckedUpdateManyInput>
  /**
   * Filter which TournamentEnrollments to update
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * Limit how many TournamentEnrollments to update.
   */
  limit?: number
}

/**
 * TournamentEnrollment updateManyAndReturn
 */
export type TournamentEnrollmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * The data used to update TournamentEnrollments.
   */
  data: Prisma.XOR<Prisma.TournamentEnrollmentUpdateManyMutationInput, Prisma.TournamentEnrollmentUncheckedUpdateManyInput>
  /**
   * Filter which TournamentEnrollments to update
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * Limit how many TournamentEnrollments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TournamentEnrollment upsert
 */
export type TournamentEnrollmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * The filter to search for the TournamentEnrollment to update in case it exists.
   */
  where: Prisma.TournamentEnrollmentWhereUniqueInput
  /**
   * In case the TournamentEnrollment found by the `where` argument doesn't exist, create a new TournamentEnrollment with this data.
   */
  create: Prisma.XOR<Prisma.TournamentEnrollmentCreateInput, Prisma.TournamentEnrollmentUncheckedCreateInput>
  /**
   * In case the TournamentEnrollment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TournamentEnrollmentUpdateInput, Prisma.TournamentEnrollmentUncheckedUpdateInput>
}

/**
 * TournamentEnrollment delete
 */
export type TournamentEnrollmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
  /**
   * Filter which TournamentEnrollment to delete.
   */
  where: Prisma.TournamentEnrollmentWhereUniqueInput
}

/**
 * TournamentEnrollment deleteMany
 */
export type TournamentEnrollmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TournamentEnrollments to delete
   */
  where?: Prisma.TournamentEnrollmentWhereInput
  /**
   * Limit how many TournamentEnrollments to delete.
   */
  limit?: number
}

/**
 * TournamentEnrollment.user
 */
export type TournamentEnrollment$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * TournamentEnrollment without action
 */
export type TournamentEnrollmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TournamentEnrollment
   */
  select?: Prisma.TournamentEnrollmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TournamentEnrollment
   */
  omit?: Prisma.TournamentEnrollmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TournamentEnrollmentInclude<ExtArgs> | null
}
